const publishers = [
    { 
        id: 0,
        name: "JioHotstar Sports", 
        niches: ["Sports", "Live Streaming"], 
        platform: "OTT / Connected TV", 
        minCpmINR: 90,
        maxCpmINR: 240,
        trafficTier: "Mass Market (50M+)",
        formats: ["Video Pre-Roll", "Video Mid-Roll", "Connected TV Banner"],
        portal: "https://magnite.com",
        channels: ["Star Sports 1 (HD/SD)", "Star Sports Select", "Star Gold", "JioCinema Regional Feeds"],
        sports: ["IPL Cricket", "ICC Tournaments", "English Premier League (EPL)", "Pro Kabaddi League"]
    },
    { 
        id: 1,
        name: "Cricbuzz", 
        niches: ["Sports"], 
        platform: "Mobile App / Web", 
        minCpmINR: 65,
        maxCpmINR: 125,
        trafficTier: "Mass Market (50M+)",
        formats: ["Banner Displays", "Audio Ads"],
        portal: "https://google.com",
        channels: ["Cricbuzz Live (Video Feed)", "Cricbuzz Comm Box (Audio)", "Regional Language Sub-pages"],
        sports: ["Domestic T20 Leagues", "Test Match Coverages", "ICC Women's World Cup"]
    },
    { 
        id: 2,
        name: "InShorts", 
        niches: ["News"], 
        platform: "Mobile App", 
        minCpmINR: 80,
        maxCpmINR: 180,
        trafficTier: "Mid-Tier Premium (10M-50M)",
        formats: ["Native In-Feed", "Banner Displays"],
        portal: "https://inshorts.com",
        channels: ["National Ticker Feed", "Tech Short Bites", "Business Pulse Channel"],
        sports: ["General Sports Highlights", "Olympic Daily Cards"]
    },
    { 
        id: 3,
        name: "Moneycontrol", 
        niches: ["Finance", "News"], 
        platform: "Web / Desktop", 
        minCpmINR: 150,
        maxCpmINR: 350,
        trafficTier: "Mid-Tier Premium (10M-50M)",
        formats: ["Native In-Feed", "Banner Displays"],
        portal: "https://moneycontrol.com",
        channels: ["MC Pro Premium", "CNBC-TV18 Live Stream Integration", "Commodities Desk Feed"],
        sports: ["IPL Brand Valuation News", "Sports Business & Finance Segment"]
    },
    { 
        id: 4,
        name: "Sportskeeda India", 
        niches: ["Sports", "Gaming"], 
        platform: "Web", 
        minCpmINR: 50,
        maxCpmINR: 110,
        trafficTier: "Mid-Tier Premium (10M-50M)",
        formats: ["Banner Displays", "Native In-Feed"],
        portal: "https://sportskeeda.com",
        channels: ["SK Wrestling Channel", "SK Esports Hub", "Cricket Analytics Desk"],
        sports: ["WWE India", "Free Fire / BGMI Esports", "Indian Football (ISL)", "La Liga"]
    },
    { 
        id: 5,
        name: "Zee5 Premium Network", 
        niches: ["General Entertainment", "Regional Content"], 
        platform: "OTT / Connected TV", 
        minCpmINR: 85,
        maxCpmINR: 210,
        trafficTier: "Mass Market (50M+)",
        formats: ["Video Pre-Roll", "Video Mid-Roll"],
        portal: "https://zee5.com",
        channels: ["Zee TV HD", "Zee Cinema", "Zee Café", "Regional Entertainment Bundles"],
        sports: ["Daily Soap Mega-Sponsorships", "Reality Show Mid-Rolls", "Regional Web-Series Placements"]
    },
    { 
        id: 6,
        name: "MX Player", 
        niches: ["General Entertainment", "Regional Content"], 
        platform: "Mobile App / Web", 
        minCpmINR: 45,
        maxCpmINR: 95,
        trafficTier: "Mass Market (50M+)",
        formats: ["Video Pre-Roll", "Video Mid-Roll", "Banner Displays"],
        portal: "https://mxplayer.in",
        channels: ["MX Original Feeds", "Vdesi (International Dubbed)", "Short Video Tickers"],
        sports: ["Web Series Video Interstitials", "Masthead Video Placements"]
    },
    { 
        id: 7,
        name: "Aha (Ahha)", 
        niches: ["Regional Content", "General Entertainment"], 
        platform: "OTT / Connected TV", 
        minCpmINR: 110,
        maxCpmINR: 260,
        trafficTier: "Niche Focused (<10M)",
        formats: ["Video Pre-Roll", "Video Mid-Roll"],
        portal: "https://aha.video",
        channels: ["Aha Telugu Live", "Aha Tamil Live", "Aha Kids corner"],
        sports: ["Regional Movie Launch Sponsorships", "Vernacular Mid-Roll Video"]
    },
    { 
        id: 8,
        name: "Amazon Prime Video", 
        niches: ["General Entertainment"], 
        platform: "OTT / Connected TV", 
        minCpmINR: 250,
        maxCpmINR: 450,
        trafficTier: "Mass Market (50M+)",
        formats: ["Video Pre-Roll", "Connected TV Banner"],
        portal: "https://amazon.com",
        channels: ["Prime Video Ad-Supported Tier", "Live Sports Broadcast Bundles"],
        sports: ["Global Live Matches", "Premium Series Pre-Rolls", "Connected TV Banner Placements"]
    },
    { 
        id: 9,
        name: "Hoichoi OTT", 
        niches: ["Regional Content", "General Entertainment"], 
        platform: "Mobile App / Web", 
        minCpmINR: 60,
        maxCpmINR: 130,
        trafficTier: "Niche Focused (<10M)",
        formats: ["Video Pre-Roll", "Banner Displays"],
        portal: "https://hoichoi.tv",
        channels: ["Bengali Originals Feed", "Hoichoi World Desk"],
        sports: ["Regional Bengali Web-Series Sponsorships", "Native UI Display In-App"]
    },
    { 
        id: 10,
        name: "Kuku TV", 
        niches: ["Regional Content", "General Entertainment"], 
        platform: "Mobile App", 
        minCpmINR: 35,
        maxCpmINR: 75,
        trafficTier: "Mid-Tier Premium (10M-50M)",
        formats: ["Audio Ads"],
        portal: "https://kukufm.com",
        channels: ["Short Audio-Serial Feeds", "Regional Story Channels"],
        sports: ["Audio In-Stream Sponsorships", "In-App Home Banner Placements"]
    },
    { 
        id: 11,
        name: "Hungama OTT", 
        niches: ["General Entertainment"], 
        platform: "Mobile App / Web", 
        minCpmINR: 40,
        maxCpmINR: 85,
        trafficTier: "Mid-Tier Premium (10M-50M)",
        formats: ["Audio Ads", "Video Mid-Roll"],
        portal: "https://hungama.com",
        channels: ["Hungama Music Stream", "Hungama Play Video Node"],
        sports: ["In-Audio Commercial Clips", "Video Mid-Roll Interstitials"]
    },
    { 
        id: 12,
        name: "Sony LIV", 
        niches: ["Sports", "General Entertainment"], 
        platform: "OTT / Connected TV", 
        minCpmINR: 120,
        maxCpmINR: 290,
        trafficTier: "Mass Market (50M+)",
        formats: ["Video Pre-Roll", "Video Mid-Roll", "Connected TV Banner"],
        portal: "https://sonyliv.com",
        channels: ["Sony LIV Sports HD", "Sony SAB Entertainment", "Sony SET National Feed"],
        sports: ["UEFA Champions League", "Cricket Bilateral Series", "Olympic Games", "WWE Premium Events"]
    },
    { 
        id: 13,
        name: "Ratri App", 
        niches: ["General Entertainment"], 
        platform: "Mobile App", 
        minCpmINR: 30,
        maxCpmINR: 65,
        trafficTier: "Niche Focused (<10M)",
        formats: ["Video Mid-Roll", "Banner Displays"],
        portal: "https://google.com",
        channels: ["Short Story Video Streams", "Adult Romance Nodes"],
        sports: ["In-Feed Mobile Video Ads", "Standard Display Interstitials"]
    },
    { 
        id: 14,
        name: "ShemarooME", 
        niches: ["General Entertainment", "Regional Content"], 
        platform: "OTT / Connected TV", 
        minCpmINR: 50,
        maxCpmINR: 120,
        trafficTier: "Mid-Tier Premium (10M-50M)",
        formats: ["Video Pre-Roll", "Connected TV Banner"],
        portal: "https://shemaroome.com",
        channels: ["Shemaroo Classic TV", "Gujarati Specialty Node", "Bhojpuri Cinema Feed"],
        sports: ["Classic Bollywood Content Wrappers", "Live Regional Broadcast Banners"]
    },
    { 
        id: 15,
        name: "Aaj Tak (aajtak.in)", 
        niches: ["News", "Live Streaming"], 
        platform: "Mobile App / Web", 
        minCpmINR: 60,
        maxCpmINR: 115,
        trafficTier: "Mass Market (50M+)",
        formats: ["Video Pre-Roll", "Video Mid-Roll", "Banner Displays"],
        portal: "https://aajtak.in",
        channels: ["Aaj Tak Live TV Stream", "Good News Today Hub", "Aaj Tak Bangla Regional Feeds"],
        sports: ["Live Debate L-Band Video Overlays", "Breaking News Push Notification Sponsorships"]
    },
    { 
        id: 16,
        name: "Netflix India", 
        niches: ["General Entertainment"], 
        platform: "OTT / Connected TV", 
        minCpmINR: 300,
        maxCpmINR: 550,
        trafficTier: "Mass Market (50M+)",
        formats: ["Video Pre-Roll"],
        portal: "https://netflix.com",
        channels: ["Netflix Standard with Ads Tier", "Top 10 Global Content Nodes"],
        sports: ["Live Exhibition Events", "Premium Series Pre-Rolls", "Unskippable Video Blocks"]
    },
    { 
        id: 17,
        name: "Jio TV", 
        niches: ["Live Streaming", "General Entertainment"], 
        platform: "Mobile App", 
        minCpmINR: 45,
        maxCpmINR: 90,
        trafficTier: "Mass Market (50M+)",
        formats: ["Video Pre-Roll", "Banner Displays"],
        portal: "https://magnite.com",
        channels: ["800+ Live Broadcast TV Channels", "Jio Darshan Feeds", "Jio Regional News Layouts"],
        sports: ["Simulcast Live Match Overlays", "Channel Switching Splash Video Ads"]
    },
    { 
        id: 18,
        name: "Spotify India", 
        niches: ["General Entertainment"], 
        platform: "Mobile App", 
        minCpmINR: 120,
        maxCpmINR: 220,
        trafficTier: "Mass Market (50M+)",
        formats: ["Audio Ads", "Video Pre-Roll"],
        portal: "https://spotify.com",
        channels: ["Spotify Free Audio Track Node", "Top Indian Podcasts Panel", "Spotify Video Takeover Link"],
        sports: ["Audio Ad Breaks (15-30s)", "Sponsored Playlist Takeovers", "Podcast Host-Read Sponsorships"]},
        {id: 19,name: "JioSaavn",niches: ["General Entertainment", "Regional Content"],platform: "Mobile App",minCpmINR: 70,maxCpmINR: 140,trafficTier: "Mid-Tier Premium (10M-50M)",formats: ["Audio Ads", "Banner Displays"],portal: "jiosaavn.com",channels: ["Saavn Free Audio Layer", "Regional Artist Showcases"],sports: ["In-Stream Audio Commercial Spots", "Interactive Mobile Audio Display Banners"]},{id: 20,name: "Times of India (indiatimes.com)",niches: ["News"],platform: "Web / App",minCpmINR: 75,maxCpmINR: 160,trafficTier: "Mass Market (50M+)",formats: ["Native In-Feed", "Banner Displays"],portal: "https://colombiaonline.com",channels: ["TOI Plus Premium Feed", "City-Specific Hyperlocal Feeds", "Gadgets Now Section"],sports: ["National News Banners", "Native In-Feed Sponsored Content Pieces"]},{id: 21,name: "NDTV (ndtv.com)",niches: ["News", "Live Streaming"],platform: "Web / App",minCpmINR: 85,maxCpmINR: 190,trafficTier: "Mid-Tier Premium (10M-50M)",formats: ["Video Pre-Roll", "Banner Displays"],portal: "ndtv.com",channels: ["NDTV 24x7 English Stream", "NDTV India Hindi Stream", "NDTV Profit Financial Node"],sports: ["Premium Homepage Masthead Video Takeovers", "In-Stream Video Pre-Roll Nodes"]},{id: 22,name: "Oneindia (oneindia.com)",niches: ["News", "Regional Content"],platform: "Web Only",minCpmINR: 35,maxCpmINR: 80,trafficTier: "Mid-Tier Premium (10M-50M)",formats: ["Native In-Feed", "Banner Displays"],portal: "oneindia.com",channels: ["Vernacular Hindi Feed", "Tamil/Telugu Core Desks", "Kannada/Malayalam Local Networks"],sports: ["Sticky Anchor Banners", "Native Outbrain Recommended Widget Placements"]},{id: 23,name: "News18 (news18.com)",niches: ["News", "Live Streaming"],platform: "Web / App",minCpmINR: 55,maxCpmINR: 130,trafficTier: "Mass Market (50M+)",formats: ["Video Pre-Roll", "Video Mid-Roll", "Banner Displays"],portal: "news18.com",channels: ["News18 Network National", "CNN-News18 Premium", "14+ Regional Indian Language Feeds"],sports: ["Live Stream Mid-Roll Ad Triggers", "Interstitials Mobile Popups"]},{id: 24,name: "India Today (indiatoday.in)",niches: ["News"],platform: "Web / App",minCpmINR: 90,maxCpmINR: 210,trafficTier: "Mid-Tier Premium (10M-50M)",formats: ["Video Pre-Roll", "Banner Displays", "Native In-Feed"],portal: "indiatoday.in",channels: ["India Today TV Live Feed", "Daily O Opinion Portal", "India Today Premium Magazine Node"],sports: ["Long-Form Editorial Sponsorship Panels", "High-Impact Video Outstream Blocks"]},{id: 25,name: "Hindustan Times (hindustantimes.com)",niches: ["News"],platform: "Web / App",minCpmINR: 70,maxCpmINR: 175,trafficTier: "Mass Market (50M+)",formats: ["Native In-Feed", "Banner Displays"],portal: "hindustantimes.com",channels: ["HT National Desk Feed", "HT Tech/Lifestyle Node", "HT Brunch Luxury Segment"],sports: ["Premium Smart-Card Content Placements", "Desktop Sidebar Sticky Banner Layouts"]},{id: 26,name: "The Hindu (thehindu.com)",niches: ["News"],platform: "Web / App",minCpmINR: 110,maxCpmINR: 250,trafficTier: "Mid-Tier Premium (10M-50M)",formats: ["Banner Displays", "Native In-Feed"],portal: "thehindu.com",channels: ["The Hindu Digital Premium", "BusinessLine Financial Nodes", "Frontline Analytical Magazine"],sports: ["Clean/Low-Clutter Premium Display Banners", "Educated/UPSC Demographics Target Filters"]},{id: 27,name: "Indian Express (indianexpress.com)",niches: ["News"],platform: "Web / App",minCpmINR: 80,maxCpmINR: 195,trafficTier: "Mid-Tier Premium (10M-50M)",formats: ["Native In-Feed", "Banner Displays"],portal: "https://indianexpress.com",channels: ["IE National Opinion Desk", "IE Express Explained Specialty Hub", "ieTamil / ieBangla Regional Nodes"],sports: ["In-Article Text Context Banner Matches", "Audio Podcast Sponsorship Audio Ads"]},{id: 28,name: "Dainik Bhaskar (bhaskar.com)",niches: ["News", "Regional Content"],platform: "Mobile App / Web",minCpmINR: 45,maxCpmINR: 105,trafficTier: "Mass Market (50M+)",formats: ["Native In-Feed", "Banner Displays"],portal: "dbcorp.in",channels: ["Dainik Bhaskar Hindi Main", "Divya Bhaskar Gujarati", "Divya Marathi Feed"],sports: ["App Splash/Welcome Interstitial Graphics", "Vernacular Regional In-Feed News Ads"]},{id: 29,name: "Jagran (jagran.com)",niches: ["News", "Regional Content"],platform: "Web / App",minCpmINR: 40,maxCpmINR: 95,trafficTier: "Mass Market (50M+)",formats: ["Native In-Feed", "Banner Displays"],portal: "jagran.com",channels: ["Dainik Jagran Core Hindi", "Jagran English Portal", "HerZindagi Women Lifestyle Segment"],sports: ["Standard Content Responsive Banner Sets", "Taboola Recommendation Ad Widgets"]},{id: 30,name: "Live Hindustan (livehindustan.com)",niches: ["News", "Regional Content"],platform: "Web Only",minCpmINR: 35,maxCpmINR: 85,trafficTier: "Mass Market (50M+)",formats: ["Native In-Feed", "Banner Displays"],portal: "livehindustan.com",channels: ["Hindi News Grid North India", "UP/Bihar Local District Channels"],sports: ["Native Dynamic Display Banner Blocks", "In-Article Outstream Autoplay Video Ads"]},{id: 31,name: "ABP Live (abplive.com)",niches: ["News", "Live Streaming"],platform: "Web / App",minCpmINR: 50,maxCpmINR: 120,trafficTier: "Mass Market (50M+)",formats: ["Video Pre-Roll", "Video Mid-Roll", "Banner Displays"],portal: "abplive.com",channels: ["ABP News Hindi Live", "ABP Ananda Bengali Feed", "ABP Majha Marathi News Stream"],sports: ["Live TV Side-Panel Dynamic Ads", "Mobile App Push-Sponsorship Trigger Slates"]},{id: 32,name: "Economic Times (economictimes.com)",niches: ["Finance", "News"],platform: "Web / Desktop",minCpmINR: 180,maxCpmINR: 400,trafficTier: "Mid-Tier Premium (10M-50M)",formats: ["Native In-Feed", "Banner Displays"],portal: "indiatimes.com",channels: ["ET Prime Premium Portal", "ET Markets Live Stock Ticker Hub", "Panache Luxury Lifestyle Segment"],sports: ["Corporate & B2B Target Overlay Panels", "High-Value Financial Demographic Takeovers"]},{id: 33,name: "Livemint (livemint.com)",niches: ["Finance", "News"],platform: "Web / Desktop",minCpmINR: 160,maxCpmINR: 380,trafficTier: "Mid-Tier Premium (10M-50M)",formats: ["Native In-Feed", "Banner Displays"],portal: "livemint.com",channels: ["Mint Premium Corporate Analytics", "Mint Lounge Culture Segments"],sports: ["Executive Tier Premium Display Placements", "In-Article Clean Native Sponsorship Links"]},{id: 34,name: "Zee News (india.com)",niches: ["News", "Live Streaming"],platform: "Web / App",minCpmINR: 50,maxCpmINR: 115,trafficTier: "Mass Market (50M+)",formats: ["Video Pre-Roll", "Video Mid-Roll", "Banner Displays"],portal: "india.com",channels: ["Zee News National Hindi Live", "Zee Business Finance News Feed", "Zee 24 Taas Regional Node"],sports: ["Streaming Pre-Roll Unskippable Ads", "Multi-Sidebar Programmatic Standard Banners"]},{id: 35,name: "DNA India (dnaindia.com)",niches: ["News"],platform: "Web Only",minCpmINR: 40,maxCpmINR: 90,trafficTier: "Mid-Tier Premium (10M-50M)",formats: ["Native In-Feed", "Banner Displays"],portal: "dnaindia.com",channels: ["DNA Originals Trending Node", "DNA Entertainment News Panel"],sports: ["Mid-Article Content Responsive Ads", "Native Context Link Recommendations"]},{id: 36,name: "Firstpost (firstpost.com)",niches: ["News"],platform: "Web Only",minCpmINR: 65,maxCpmINR: 140,trafficTier: "Mid-Tier Premium (10M-50M)",formats: ["Video Pre-Roll", "Native In-Feed", "Banner Displays"],portal: "firstpost.com",channels: ["Firstpost Global Show Video Node", "Firstpost Vantage Analytical Desk"],sports: ["Global Viewers Outstream Video Placements", "Premium Editorial Sponsorship Header Blocks"]},{id: 37,name: "Business Standard (business-standard.com)",niches: ["Finance", "News"],platform: "Web / Desktop",minCpmINR: 140,maxCpmINR: 320,trafficTier: "Mid-Tier Premium (10M-50M)",formats: ["Native In-Feed", "Banner Displays"],portal: "business-standard.com",channels: ["BS Premium Financial Analytics", "BS Corporate Strategy Columns"],sports: ["B2B Decision Makers Banner Filters", "Clean Text-Matched Advertising Ad-Units"]},{id: 38,name: "BBC News India (bbc.com)",niches: ["News", "International Network"],platform: "Web / App",minCpmINR: 150,maxCpmINR: 300,trafficTier: "Mid-Tier Premium (10M-50M)",formats: ["Video Pre-Roll", "Banner Displays"],portal: "bbc.com",channels: ["BBC World News Global Hub", "BBC Hindi / Tamil Language Desks", "BBC Marathi Analytical Node"],sports: ["Strict Brand-Safe Premium Banner Placements", "International Quality Outstream Video Blocks"]},  
        {
    id: 39,
    name: "FanCode", 
    niches: ["Sports", "Live Streaming"], 
    platform: "Mobile App / Web", 
    minCpmINR: 110,
    maxCpmINR: 260,
    trafficTier: "Mid-Tier Premium (10M-50M)",
    formats: ["Video Pre-Roll", "Video Mid-Roll", "Banner Displays"],
    portal: "https://fancode.com",
    channels: ["FanCode Live Main Feed", "Dream Sports Ad Exchange Node", "Regional Language Commentary Slates"],
    sports: ["Bilateral Cricket Tours", "Hero I-League", "Super Smash T20", "Caraba Cup", "Major League Cricket"]
},
{ 
    id: 40,
    name: "DAZN India", 
    niches: ["Sports", "International Network"], 
    platform: "OTT / Connected TV", 
    minCpmINR: 180,
    maxCpmINR: 420,
    trafficTier: "Niche Focused (<10M)",
    formats: ["Video Pre-Roll", "Connected TV Banner"],
    portal: "https://daznmedia.com",
    channels: ["DAZN Fight Channel", "DAZN Motorsport Stream Node", "Global Premium Soccer Feeds"],
    sports: ["Championship Boxing", "MMA Match Cards", "International Motorsports", "Premium European Football"]
},
{ 
    id: 41,
    name: "SportVot", 
    niches: ["Sports", "Regional Content"], 
    platform: "Mobile App / Web", 
    minCpmINR: 35,
    maxCpmINR: 75,
    trafficTier: "Niche Focused (<10M)",
    formats: ["Video Pre-Roll", "Banner Displays", "Native In-Feed"],
    portal: "https://sportvot.com",
    channels: ["State Tournament Streams", "District Sports Hub", "Grassroots Athlete Profiles Page"],
    sports: ["Local Kabaddi Leagues", "Corporate Cricket Cups", "State-Level Football Championships"]
},
{ 
    id: 42,
    name: "TV9 Marathi",
    niches: ["News", "Regional Content", "Live Streaming"],
    platform: "Web / App / TV",
    minCpmINR: 45,
    maxCpmINR: 110,
    trafficTier: "Mass Market (50M+)",
    formats: ["Video Pre-Roll", "Video Mid-Roll", "Banner Displays"],
    portal: "https://www.tv9marathi.com",
    channels: ["TV9 Marathi Live", "Maharashtra News", "Mumbai News", "Pune News"],
    sports: ["Marathi Sports News", "Cricket Coverage"]
},
{ 
    id: 43,
    name: "Zee 24 Taas",
    niches: ["News", "Regional Content", "Live Streaming"],
    platform: "Web / App / TV",
    minCpmINR: 40,
    maxCpmINR: 100,
    trafficTier: "Mass Market (50M+)",
    formats: ["Video Pre-Roll", "Video Mid-Roll", "Banner Displays"],
    portal: "https://zee24taas.in",
    channels: ["Zee 24 Taas Live", "Maharashtra News", "Mumbai News"],
    sports: ["Marathi Sports Coverage"]
},
{ 
    id: 44,
    name: "ABP Majha",
    niches: ["News", "Regional Content", "Live Streaming"],
    platform: "Web / App / TV",
    minCpmINR: 45,
    maxCpmINR: 110,
    trafficTier: "Mass Market (50M+)",
    formats: ["Video Pre-Roll", "Video Mid-Roll", "Banner Displays"],
    portal: "https://marathi.abplive.com",
    channels: ["ABP Majha Live", "Maharashtra News", "Mumbai News", "Pune News"],
    sports: ["Cricket News", "Maharashtra Sports"]
},
{ 
    id: 45,
    name: "News18 Lokmat",
    niches: ["News", "Regional Content", "Live Streaming"],
    platform: "Web / App / TV",
    minCpmINR: 40,
    maxCpmINR: 100,
    trafficTier: "Mass Market (50M+)",
    formats: ["Video Pre-Roll", "Video Mid-Roll", "Banner Displays"],
    portal: "https://lokmat.news18.com",
    channels: ["News18 Lokmat Live", "Maharashtra News", "Mumbai News", "Sports Time"],
    sports: ["Maharashtra Sports", "Cricket Coverage"]
},
{ 
    id: 46,
    name: "Saam TV",
    niches: ["News", "Regional Content", "Live Streaming"],
    platform: "Web / App / TV",
    minCpmINR: 35,
    maxCpmINR: 90,
    trafficTier: "Mid-Tier Premium (10M-50M)",
    formats: ["Video Pre-Roll", "Video Mid-Roll", "Banner Displays"],
    portal: "https://saamtv.com",
    channels: ["Saam TV Live", "Maharashtra News", "Mumbai News"],
    sports: ["Regional Sports News"]
},
{ 
    id: 47,
    name: "Lokmat",
    niches: ["News", "Regional Content"],
    platform: "Web / App / Print",
    minCpmINR: 40,
    maxCpmINR: 100,
    trafficTier: "Mass Market (50M+)",
    formats: ["Native In-Feed", "Banner Displays", "Video Pre-Roll"],
    portal: "https://www.lokmat.com",
    channels: ["Lokmat Marathi", "Mumbai", "Pune", "Nagpur", "Nashik"],
    sports: ["Cricket", "Maharashtra Sports"]
},
{ 
    id: 48,
    name: "NDTV Marathi",
    niches: ["News", "Regional Content", "Live Streaming"],
    platform: "Web / App / TV",
    minCpmINR: 50,
    maxCpmINR: 120,
    trafficTier: "Mid-Tier Premium (10M-50M)",
    formats: ["Video Pre-Roll", "Video Mid-Roll", "Banner Displays"],
    portal: "https://marathi.ndtv.com",
    channels: ["NDTV Marathi Live", "Maharashtra News", "Mumbai News", "Nagpur News"],
    sports: ["Cricket News", "Regional Sports"]
},
{ 
    id: 49,
    name: "Jai Maharashtra",
    niches: ["News", "Regional Content", "Live Streaming"],
    platform: "Web / App / TV",
    minCpmINR: 30,
    maxCpmINR: 80,
    trafficTier: "Niche Focused (<10M)",
    formats: ["Video Pre-Roll", "Video Mid-Roll", "Banner Displays"],
    portal: "https://jaimaharashtranews.com",
    channels: ["Jai Maharashtra Live", "Maharashtra News", "Mumbai News"],
    sports: ["Regional Sports Coverage"]
},
{ 
    id: 50,
    name: "Maharashtra Times",
    niches: ["News", "Regional Content"],
    platform: "Web / App / Print",
    minCpmINR: 50,
    maxCpmINR: 125,
    trafficTier: "Mass Market (50M+)",
    formats: ["Native In-Feed", "Banner Displays", "Video Pre-Roll"],
    portal: "https://maharashtratimes.com",
    channels: ["Maharashtra Times Marathi", "Mumbai", "Pune", "Nagpur", "Nashik"],
    sports: ["Cricket", "Maharashtra Sports"]
},
{ 
    id: 51,
    name: "DD Sahyadri",
    niches: ["News", "Regional Content", "General Entertainment"],
    platform: "TV / Digital",
    minCpmINR: 25,
    maxCpmINR: 70,
    trafficTier: "Mass Market (50M+)",
    formats: ["Video Pre-Roll", "Video Mid-Roll"],
    portal: "https://www.prasarbharati.gov.in",
    channels: ["DD Sahyadri", "Marathi News", "Marathi Cultural Programming"],
    sports: ["Regional Sports Coverage"]
},
{ 
    id: 52,
    name: "Punya Nagari",
    niches: ["News", "Regional Content"],
    platform: "Web / Print",
    minCpmINR: 30,
    maxCpmINR: 75,
    trafficTier: "Mid-Tier Premium (10M-50M)",
    formats: ["Native In-Feed", "Banner Displays"],
    portal: "https://www.dainikpunyanagari.com",
    channels: ["Punya Nagari Marathi", "Maharashtra Local News"],
    sports: ["Cricket", "Regional Sports"]
},
{ 
    id: 53,
    name: "Sakal",
    niches: ["News", "Regional Content"],
    platform: "Web / App / Print",
    minCpmINR: 40,
    maxCpmINR: 100,
    trafficTier: "Mass Market (50M+)",
    formats: ["Native In-Feed", "Banner Displays", "Video Pre-Roll"],
    portal: "https://www.esakal.com",
    channels: ["Sakal Marathi", "Pune", "Mumbai", "Nagpur", "Nashik"],
    sports: ["Cricket", "Maharashtra Sports"]
},
  { id: 54, name: "Sun News Tamil", niches: ["News", "Regional Content", "Live Streaming"], platform: "Web / App / TV", minCpmINR: 45, maxCpmINR: 110, trafficTier: "Mass Market (50M+)" },
  { id: 55, name: "Polimer News", niches: ["News", "Regional Content"], platform: "Web / App", minCpmINR: 35, maxCpmINR: 85, trafficTier: "Mass Market (50M+)" },
  { id: 56, name: "Thanthi TV", niches: ["News", "Regional Content", "Live Streaming"], platform: "Web / App / TV", minCpmINR: 40, maxCpmINR: 95, trafficTier: "Mass Market (50M+)" },
  { id: 57, name: "Puthiya Thalaimurai", niches: ["News", "Regional Content"], platform: "Web / App / TV", minCpmINR: 45, maxCpmINR: 105, trafficTier: "Mid-Tier Premium (10M-50M)" },
  { id: 58, name: "TV9 Telugu", niches: ["News", "Regional Content", "Live Streaming"], platform: "Web / App / TV", minCpmINR: 50, maxCpmINR: 120, trafficTier: "Mass Market (50M+)" },
  { id: 59, name: "NTV Telugu", niches: ["News", "Regional Content"], platform: "Web / App / TV", minCpmINR: 45, maxCpmINR: 110, trafficTier: "Mass Market (50M+)" },
  { id: 60, name: "V6 News Telugu", niches: ["News", "Regional Content"], platform: "Web / App", minCpmINR: 35, maxCpmINR: 80, trafficTier: "Mid-Tier Premium (10M-50M)" },
  { id: 61, name: "TV9 Kannada", niches: ["News", "Regional Content", "Live Streaming"], platform: "Web / App / TV", minCpmINR: 45, maxCpmINR: 110, trafficTier: "Mass Market (50M+)" },
  { id: 62, name: "Suvarna News", niches: ["News", "Regional Content"], platform: "Web / App", minCpmINR: 40, maxCpmINR: 95, trafficTier: "Mass Market (50M+)" },
  { id: 63, name: "Public TV Kannada", niches: ["News", "Regional Content"], platform: "Web / App", minCpmINR: 35, maxCpmINR: 85, trafficTier: "Mid-Tier Premium (10M-50M)" },
  { id: 64, name: "Asianet News Malayalam", niches: ["News", "Regional Content", "Live Streaming"], platform: "Web / App / TV", minCpmINR: 50, maxCpmINR: 125, trafficTier: "Mass Market (50M+)" },
  { id: 65, name: "24 News Malayalam", niches: ["News", "Regional Content"], platform: "Web / App / TV", minCpmINR: 45, maxCpmINR: 105, trafficTier: "Mass Market (50M+)" },
  { id: 66, name: "TV9 Bangla", niches: ["News", "Regional Content", "Live Streaming"], platform: "Web / App / TV", minCpmINR: 40, maxCpmINR: 100, trafficTier: "Mass Market (50M+)" },
  { id: 67, name: "Zee 24 Ghanta", niches: ["News", "Regional Content"], platform: "Web / App / TV", minCpmINR: 45, maxCpmINR: 110, trafficTier: "Mass Market (50M+)" },
  { id: 68, name: "TV9 Gujarati", niches: ["News", "Regional Content"], platform: "Web / App / TV", minCpmINR: 40, maxCpmINR: 95, trafficTier: "Mass Market (50M+)" },
  { id: 69, name: "Sandesh News", niches: ["News", "Regional Content"], platform: "Web / App / Print", minCpmINR: 35, maxCpmINR: 85, trafficTier: "Mid-Tier Premium (10M-50M)" },
  { id: 70, name: "PTC News Punjabi", niches: ["News", "Regional Content", "General Entertainment"], platform: "Web / App / TV", minCpmINR: 40, maxCpmINR: 90, trafficTier: "Mid-Tier Premium (10M-50M)" },
  { id: 71, name: "Pocket FM", niches: ["Audio", "Regional Content"], platform: "Mobile App", minCpmINR: 60, maxCpmINR: 130, trafficTier: "Mass Market (50M+)" },
  { id: 72, name: "Aha Tamil", niches: ["Regional Content", "General Entertainment"], platform: "OTT / Connected TV", minCpmINR: 110, maxCpmINR: 250, trafficTier: "Mid-Tier Premium (10M-50M)" },
  { id: 73, name: "WinZO Ad Network", niches: ["Gaming", "Entertainment"], platform: "Mobile App", minCpmINR: 50, maxCpmINR: 110, trafficTier: "Mass Market (50M+)" },
  { id: 74, name: "BQ Prime (Bloomberg)", niches: ["Finance", "Business"], platform: "Web / Desktop", minCpmINR: 190, maxCpmINR: 420, trafficTier: "Niche Focused (<10M)" },
  { id: 75, name: "Inc42 Media", niches: ["Business", "Startups"], platform: "Web / Desktop", minCpmINR: 140, maxCpmINR: 310, trafficTier: "Niche Focused (<10M)" },
    { id: 76, name: "JioCinema Ads", niches: ["OTT", "Sports", "General Entertainment"], platform: "OTT / Connected TV", minCpmINR: 100, maxCpmINR: 280, trafficTier: "Mass Market (50M+)" },
  { id: 77, name: "Manorama Online", niches: ["News", "Regional Content"], platform: "Web / Mobile App", minCpmINR: 50, maxCpmINR: 130, trafficTier: "Mass Market (50M+)" },
  { id: 78, name: "Eenadu Digital", niches: ["News", "Regional Content"], platform: "Web / Mobile App", minCpmINR: 45, maxCpmINR: 115, trafficTier: "Mass Market (50M+)" },
  { id: 79, name: "ABP Ananda", niches: ["News", "Regional Content", "Live Streaming"], platform: "Web / App / TV", minCpmINR: 40, maxCpmINR: 105, trafficTier: "Mass Market (50M+)" },
  { id: 80, name: "Mathrubhumi", niches: ["News", "Regional Content"], platform: "Web / App / Print", minCpmINR: 45, maxCpmINR: 110, trafficTier: "Mass Market (50M+)" },
  { id: 81, name: "Sakshi Post", niches: ["News", "Regional Content"], platform: "Web / App", minCpmINR: 40, maxCpmINR: 95, trafficTier: "Mass Market (50M+)" },
  { id: 82, name: "Dinakaran", niches: ["News", "Regional Content"], platform: "Web / Print", minCpmINR: 35, maxCpmINR: 85, trafficTier: "Mid-Tier Premium (10M-50M)" },
  { id: 83, name: "Divya Bhaskar", niches: ["News", "Regional Content"], platform: "Web / App", minCpmINR: 40, maxCpmINR: 100, trafficTier: "Mass Market (50M+)" },
  { id: 84, name: "Dailyhunt Network", niches: ["News", "Regional Content", "Aggregator"], platform: "Mobile App", minCpmINR: 35, maxCpmINR: 80, trafficTier: "Mass Market (50M+)" },
  { id: 85, name: "ShareChat Ad Network", niches: ["Regional Content", "Social Media"], platform: "Mobile App", minCpmINR: 45, maxCpmINR: 95, trafficTier: "Mass Market (50M+)" },
  { id: 86, name: "Moj Short Video", niches: ["Entertainment", "Regional Content"], platform: "Mobile App", minCpmINR: 50, maxCpmINR: 110, trafficTier: "Mass Market (50M+)" },
  { id: 87, name: "The Quint", niches: ["News", "Youth & Culture"], platform: "Web / Mobile App", minCpmINR: 70, maxCpmINR: 160, trafficTier: "Mid-Tier Premium (10M-50M)" },
  { id: 88, name: "ScoopWhoop", niches: ["Entertainment", "Youth & Culture"], platform: "Web / Social Platforms", minCpmINR: 60, maxCpmINR: 140, trafficTier: "Mid-Tier Premium (10M-50M)" },
  { id: 89, name: "Kuku FM", niches: ["Audio", "Regional Content"], platform: "Mobile App", minCpmINR: 55, maxCpmINR: 120, trafficTier: "Mass Market (50M+)" },
  { id: 90, name: "Glance Lockscreen Network", niches: ["News", "Gaming", "Entertainment"], platform: "Mobile Lockscreen", minCpmINR: 65, maxCpmINR: 150, trafficTier: "Mass Market (50M+)" },
  { id: 91, name: "Outlook India", niches: ["News", "Business"], platform: "Web / Magazine", minCpmINR: 90, maxCpmINR: 210, trafficTier: "Mid-Tier Premium (10M-50M)" },
  { id: 92, name: "YourStory", niches: ["Business", "Startups"], platform: "Web / Desktop", minCpmINR: 130, maxCpmINR: 290, trafficTier: "Niche Focused (<10M)" },
  { id: 93, name: "TVF (The Viral Fever)", niches: ["General Entertainment", "Youth Content"], platform: "OTT / Web", minCpmINR: 120, maxCpmINR: 270, trafficTier: "Mid-Tier Premium (10M-50M)" },
  { id: 94, name: "Namma Flix", niches: ["Regional Content", "General Entertainment"], platform: "OTT / Mobile App", minCpmINR: 50, maxCpmINR: 115, trafficTier: "Niche Focused (<10M)" },
  { id: 95, name: "Planet Marathi OTT", niches: ["Regional Content", "General Entertainment"], platform: "OTT / Connected TV", minCpmINR: 60, maxCpmINR: 135, trafficTier: "Niche Focused (<10M)" },
    { id: 96, name: "ET Now / ET Now Swadesh", niches: ["Finance", "Business", "News"], platform: "Web / TV / App", minCpmINR: 110, maxCpmINR: 260, trafficTier: "Mid-Tier Premium (10M-50M)" },
  { id: 97, name: "CNBC-TV18 / CNBC Awaaz", niches: ["Finance", "Business", "News"], platform: "Web / TV / App", minCpmINR: 130, maxCpmINR: 290, trafficTier: "Mid-Tier Premium (10M-50M)" },
  { id: 98, name: "Moneycontrol Pro", niches: ["Finance", "Investments"], platform: "Web / Mobile App", minCpmINR: 180, maxCpmINR: 380, trafficTier: "Mid-Tier Premium (10M-50M)" },
  { id: 99, name: "Groww Digest & Media", niches: ["Finance", "Investments"], platform: "Mobile App / Web", minCpmINR: 150, maxCpmINR: 320, trafficTier: "Mass Market (50M+)" },
  { id: 100, name: "Zerodha Varsity & Pulse", niches: ["Finance", "Education"], platform: "Web / Mobile App", minCpmINR: 140, maxCpmINR: 300, trafficTier: "Mid-Tier Premium (10M-50M)" },
  { id: 101, name: "Financial Express", niches: ["Finance", "Business"], platform: "Web / Desktop", minCpmINR: 120, maxCpmINR: 270, trafficTier: "Mid-Tier Premium (10M-50M)" },
  { id: 102, name: "Fortune India", niches: ["Business", "Leadership"], platform: "Web / Magazine", minCpmINR: 160, maxCpmINR: 350, trafficTier: "Niche Focused (<10M)" },
  { id: 103, name: "Forbes India", niches: ["Business", "Leadership"], platform: "Web / Magazine", minCpmINR: 170, maxCpmINR: 380, trafficTier: "Niche Focused (<10M)" },
  { id: 104, name: "Business Today", niches: ["Business", "Finance"], platform: "Web / Mobile App", minCpmINR: 130, maxCpmINR: 280, trafficTier: "Mid-Tier Premium (10M-50M)" },
  { id: 105, name: "Entrackr", niches: ["Business", "Startups", "Tech"], platform: "Web / Desktop", minCpmINR: 110, maxCpmINR: 240, trafficTier: "Niche Focused (<10M)" },
  { id: 106, name: "Gadgets 360 (NDTV Tech)", niches: ["Technology", "Gadgets"], platform: "Web / Mobile App", minCpmINR: 90, maxCpmINR: 200, trafficTier: "Mass Market (50M+)" },
  { id: 107, name: "91mobiles", niches: ["Technology", "Gadgets"], platform: "Web / Mobile", minCpmINR: 80, maxCpmINR: 180, trafficTier: "Mid-Tier Premium (10M-50M)" },
  { id: 108, name: "Digit.in", niches: ["Technology", "Gaming"], platform: "Web / Desktop", minCpmINR: 75, maxCpmINR: 165, trafficTier: "Mid-Tier Premium (10M-50M)" },
  { id: 109, name: "ZigWheels", niches: ["Automotive"], platform: "Web / Mobile App", minCpmINR: 100, maxCpmINR: 230, trafficTier: "Mid-Tier Premium (10M-50M)" },
  { id: 110, name: "CarDekho Network", niches: ["Automotive"], platform: "Web / Mobile App", minCpmINR: 110, maxCpmINR: 250, trafficTier: "Mass Market (50M+)" },
  { id: 111, name: "CarWale", niches: ["Automotive"], platform: "Web / Mobile App", minCpmINR: 105, maxCpmINR: 240, trafficTier: "Mid-Tier Premium (10M-50M)" },
  { id: 112, name: "Autocar India", niches: ["Automotive"], platform: "Web / Magazine", minCpmINR: 95, maxCpmINR: 220, trafficTier: "Mid-Tier Premium (10M-50M)" },
  { id: 113, name: "Pinkvilla", niches: ["Entertainment", "Lifestyle", "Bollywood"], platform: "Web / Social", minCpmINR: 70, maxCpmINR: 150, trafficTier: "Mass Market (50M+)" },
  { id: 114, name: "Bollywood Hungama", niches: ["Entertainment", "Bollywood"], platform: "Web / Mobile App", minCpmINR: 65, maxCpmINR: 140, trafficTier: "Mid-Tier Premium (10M-50M)" },
  { id: 115, name: "MissMalini", niches: ["Lifestyle", "Fashion", "Entertainment"], platform: "Web / Social", minCpmINR: 85, maxCpmINR: 190, trafficTier: "Niche Focused (<10M)" },
  { id: 116, name: "Loco Gaming Network", niches: ["Gaming", "Live Streaming"], platform: "Mobile App / Web", minCpmINR: 60, maxCpmINR: 130, trafficTier: "Mid-Tier Premium (10M-50M)" },
  { id: 117, name: "Rooter Streaming", niches: ["Gaming", "Esports"], platform: "Mobile App", minCpmINR: 55, maxCpmINR: 125, trafficTier: "Mass Market (50M+)" },
  { id: 118, name: "MPL (Mobile Premier League) Ads", niches: ["Gaming", "Sports"], platform: "Mobile App", minCpmINR: 65, maxCpmINR: 140, trafficTier: "Mass Market (50M+)" },
  { id: 119, name: "Nodwin Gaming Network", niches: ["Esports", "Gaming"], platform: "Digital / OTT / Events", minCpmINR: 120, maxCpmINR: 260, trafficTier: "Mid-Tier Premium (10M-50M)" },
  { id: 120, name: "Adda247", niches: ["Education", "Jobs"], platform: "Web / Mobile App", minCpmINR: 40, maxCpmINR: 90, trafficTier: "Mass Market (50M+)" },
  { id: 121, name: "Testbook", niches: ["Education", "Jobs"], platform: "Web / Mobile App", minCpmINR: 45, maxCpmINR: 95, trafficTier: "Mass Market (50M+)" },
  { id: 122, name: "SarkariResult", niches: ["Jobs", "Education"], platform: "Web / Desktop", minCpmINR: 30, maxCpmINR: 70, trafficTier: "Mass Market (50M+)" },
  { id: 123, name: "FilterCopy (Pocket Aces)", niches: ["Entertainment", "Youth & Culture"], platform: "Social Video / Web", minCpmINR: 90, maxCpmINR: 210, trafficTier: "Mass Market (50M+)" },
  { id: 124, name: "Being Indian / Culture Machine", niches: ["Entertainment", "Youth & Culture"], platform: "Social Video", minCpmINR: 70, maxCpmINR: 155, trafficTier: "Mid-Tier Premium (10M-50M)" },
  { id: 125, name: "MensXP", niches: ["Lifestyle", "Men's Fashion"], platform: "Web / Social", minCpmINR: 80, maxCpmINR: 175, trafficTier: "Mid-Tier Premium (10M-50M)" },
  { id: 126, name: "Amar Ujala", niches: ["News", "Regional Content"], platform: "Web / App / Print", minCpmINR: 40, maxCpmINR: 95, trafficTier: "Mass Market (50M+)" },
  { id: 127, name: "Navbharat Times", niches: ["News", "Regional Content"], platform: "Web / App / Print", minCpmINR: 45, maxCpmINR: 105, trafficTier: "Mass Market (50M+)" },
  { id: 128, name: "Prabhat Khabar", niches: ["News", "Regional Content"], platform: "Web / Print", minCpmINR: 35, maxCpmINR: 80, trafficTier: "Mid-Tier Premium (10M-50M)" },
  { id: 129, name: "Rajasthan Patrika", niches: ["News", "Regional Content"], platform: "Web / App / Print", minCpmINR: 40, maxCpmINR: 95, trafficTier: "Mass Market (50M+)" },
  { id: 130, name: "Hindustan Dainik", niches: ["News", "Regional Content"], platform: "Web / App / Print", minCpmINR: 40, maxCpmINR: 95, trafficTier: "Mass Market (50M+)" },
  { id: 131, name: "Anandabazar Patrika (ABP)", niches: ["News", "Regional Content"], platform: "Web / App / Print", minCpmINR: 50, maxCpmINR: 115, trafficTier: "Mass Market (50M+)" },
  { id: 132, name: "Eisamay (Times Group)", niches: ["News", "Regional Content"], platform: "Web / App / Print", minCpmINR: 40, maxCpmINR: 90, trafficTier: "Mid-Tier Premium (10M-50M)" },
  { id: 133, name: "Dinamalar", niches: ["News", "Regional Content"], platform: "Web / App / Print", minCpmINR: 40, maxCpmINR: 95, trafficTier: "Mass Market (50M+)" },
  { id: 134, name: "Dinakaran Digital", niches: ["News", "Regional Content"], platform: "Web / App", minCpmINR: 35, maxCpmINR: 85, trafficTier: "Mid-Tier Premium (10M-50M)" },
  { id: 135, name: "Prajavani", niches: ["News", "Regional Content"], platform: "Web / App / Print", minCpmINR: 40, maxCpmINR: 90, trafficTier: "Mid-Tier Premium (10M-50M)" },
  { id: 136, name: "Gaana (Times Internet)", niches: ["Audio", "General Entertainment"], platform: "Mobile App", minCpmINR: 65, maxCpmINR: 135, trafficTier: "Mass Market (50M+)" },
  { id: 137, name: "Wynk Music", niches: ["Audio", "General Entertainment"], platform: "Mobile App", minCpmINR: 60, maxCpmINR: 125, trafficTier: "Mass Market (50M+)" },
  { id: 138, name: "Audible India", niches: ["Audio", "Books & Podcasts"], platform: "Mobile App", minCpmINR: 110, maxCpmINR: 240, trafficTier: "Mid-Tier Premium (10M-50M)" },
  { id: 139, name: "Hubhopper Ad Network", niches: ["Audio", "Podcasts"], platform: "Mobile App / Web", minCpmINR: 70, maxCpmINR: 150, trafficTier: "Niche Focused (<10M)" },
  { id: 140, name: "RedFM Digital / Podcast", niches: ["Audio", "Regional Content"], platform: "Mobile App / Web", minCpmINR: 60, maxCpmINR: 130, trafficTier: "Mid-Tier Premium (10M-50M)" },
  { id: 141, name: "Radio Mirchi Digital (Mirchi.in)", niches: ["Audio", "Entertainment"], platform: "Mobile App / Web", minCpmINR: 65, maxCpmINR: 140, trafficTier: "Mid-Tier Premium (10M-50M)" },
  { id: 142, name: "SheThePeople.TV", niches: ["Women", "Culture", "News"], platform: "Web / Social", minCpmINR: 75, maxCpmINR: 170, trafficTier: "Niche Focused (<10M)" },
  { id: 143, name: "PopXo (MyGlamm Media)", niches: ["Fashion", "Beauty", "Women"], platform: "Web / Mobile App", minCpmINR: 85, maxCpmINR: 185, trafficTier: "Mid-Tier Premium (10M-50M)" },
  { id: 144, name: "The Better India", niches: ["Social Impact", "News", "Culture"], platform: "Web / Social", minCpmINR: 80, maxCpmINR: 180, trafficTier: "Mid-Tier Premium (10M-50M)" },
  { id: 145, name: "Curly Tales", niches: ["Travel", "Food", "Lifestyle"], platform: "Web / Social Video", minCpmINR: 95, maxCpmINR: 220, trafficTier: "Mid-Tier Premium (10M-50M)" },
    { id: 146, name: "MagicBricks Media Network", niches: ["Real Estate", "Home & Living"], platform: "Web / App", minCpmINR: 140, maxCpmINR: 310, trafficTier: "Mid-Tier Premium (10M-50M)" },
  { id: 147, name: "99acres Advertising", niches: ["Real Estate", "Property"], platform: "Web / App", minCpmINR: 130, maxCpmINR: 290, trafficTier: "Mid-Tier Premium (10M-50M)" },
  { id: 148, name: "Housing.com Ads", niches: ["Real Estate", "Interior Design"], platform: "Web / Mobile App", minCpmINR: 120, maxCpmINR: 270, trafficTier: "Mid-Tier Premium (10M-50M)" },
  { id: 149, name: "Shiksha.com Network", niches: ["Education", "Careers"], platform: "Web / Desktop", minCpmINR: 90, maxCpmINR: 200, trafficTier: "Mid-Tier Premium (10M-50M)" },
  { id: 150, name: "CollegeDekho", niches: ["Education", "Careers"], platform: "Web / Mobile", minCpmINR: 85, maxCpmINR: 190, trafficTier: "Mid-Tier Premium (10M-50M)" },
  { id: 151, name: "BookMyShow Ads", niches: ["Entertainment", "Movies & Events"], platform: "Mobile App / Web", minCpmINR: 150, maxCpmINR: 330, trafficTier: "Mass Market (50M+)" },
  { id: 152, name: "MakeMyTrip Media Network", niches: ["Travel", "Hospitality"], platform: "Mobile App / Web", minCpmINR: 160, maxCpmINR: 350, trafficTier: "Mass Market (50M+)" },
  { id: 153, name: "Ixigo Ads", niches: ["Travel", "Transport"], platform: "Mobile App", minCpmINR: 110, maxCpmINR: 250, trafficTier: "Mass Market (50M+)" },
  { id: 154, name: "Paytm Ad Network", niches: ["Fintech", "E-commerce"], platform: "Mobile App", minCpmINR: 120, maxCpmINR: 280, trafficTier: "Mass Market (50M+)" },
  { id: 155, name: "PhonePe Ads", niches: ["Fintech", "Payments"], platform: "Mobile App", minCpmINR: 130, maxCpmINR: 290, trafficTier: "Mass Market (50M+)" },
  { id: 156, name: "Sportskeeda", niches: ["Sports", "Cricket", "Gaming"], platform: "Web / Mobile App", minCpmINR: 75, maxCpmINR: 170, trafficTier: "Mass Market (50M+)" },
  { id: 157, name: "Cricbuzz", niches: ["Sports", "Cricket"], platform: "Web / Mobile App", minCpmINR: 120, maxCpmINR: 300, trafficTier: "Mass Market (50M+)" },
  { id: 158, name: "ESPNCricinfo India", niches: ["Sports", "Cricket"], platform: "Web / Mobile App", minCpmINR: 130, maxCpmINR: 320, trafficTier: "Mass Market (50M+)" },
  { id: 159, name: "MyUpchar", niches: ["Health & Wellness", "Regional Content"], platform: "Web / Mobile App", minCpmINR: 50, maxCpmINR: 120, trafficTier: "Mass Market (50M+)" },
  { id: 160, name: "1mg Health Media Network", niches: ["Health & Wellness", "Pharma"], platform: "Web / Mobile App", minCpmINR: 140, maxCpmINR: 300, trafficTier: "Mid-Tier Premium (10M-50M)" },
  { id: 161, name: "HealthifyMe Ads", niches: ["Fitness", "Health & Wellness"], platform: "Mobile App", minCpmINR: 150, maxCpmINR: 320, trafficTier: "Mid-Tier Premium (10M-50M)" },
  { id: 162, name: "Cult.fit Media", niches: ["Fitness", "Lifestyle"], platform: "Mobile App", minCpmINR: 160, maxCpmINR: 340, trafficTier: "Mid-Tier Premium (10M-50M)" },
  { id: 163, name: "Goal.com India", niches: ["Sports", "Football"], platform: "Web / Mobile", minCpmINR: 80, maxCpmINR: 180, trafficTier: "Mid-Tier Premium (10M-50M)" },
  { id: 164, name: "FanCode Network", niches: ["Sports", "Live Streaming"], platform: "Mobile App / OTT", minCpmINR: 110, maxCpmINR: 250, trafficTier: "Mid-Tier Premium (10M-50M)" },
  { id: 165, name: "Dream11 In-App Network", niches: ["Sports", "Gaming"], platform: "Mobile App", minCpmINR: 140, maxCpmINR: 320, trafficTier: "Mass Market (50M+)" },
  { id: 166, name: "Beebom", niches: ["Technology", "Gadgets", "How-To"], platform: "Web / Social Video", minCpmINR: 85, maxCpmINR: 190, trafficTier: "Mid-Tier Premium (10M-50M)" },
  { id: 167, name: "TechPP (Technology Personalized)", niches: ["Technology", "Gadgets"], platform: "Web / Desktop", minCpmINR: 70, maxCpmINR: 160, trafficTier: "Niche Focused (<10M)" },
  { id: 168, name: "Analytics India Magazine (AIM)", niches: ["Technology", "AI & Data Science"], platform: "Web / Desktop", minCpmINR: 160, maxCpmINR: 360, trafficTier: "Niche Focused (<10M)" },
  { id: 169, name: "Inc42", niches: ["Business", "Startups", "Tech"], platform: "Web / Desktop", minCpmINR: 150, maxCpmINR: 340, trafficTier: "Niche Focused (<10M)" },
  { id: 170, name: "Trak.in", niches: ["Business", "Tech", "Telecom"], platform: "Web / Mobile", minCpmINR: 75, maxCpmINR: 165, trafficTier: "Mid-Tier Premium (10M-50M)" },
  { id: 171, name: "Sify.com", niches: ["News", "Tech", "Business"], platform: "Web / Desktop", minCpmINR: 60, maxCpmINR: 135, trafficTier: "Mid-Tier Premium (10M-50M)" },
  { id: 172, name: "Devami / TechGig Network", niches: ["Technology", "Coding & Jobs"], platform: "Web / Mobile", minCpmINR: 95, maxCpmINR: 210, trafficTier: "Mid-Tier Premium (10M-50M)" },
  { id: 173, name: "GeeksforGeeks Ads", niches: ["Education", "Coding & Tech"], platform: "Web / Mobile App", minCpmINR: 80, maxCpmINR: 175, trafficTier: "Mass Market (50M+)" },
  { id: 174, name: "IndiaTimes Lifestyle Network", niches: ["Lifestyle", "Youth & Culture"], platform: "Web / Social", minCpmINR: 75, maxCpmINR: 165, trafficTier: "Mass Market (50M+)" },
  { id: 175, name: "Youth Ki Awaaz", niches: ["Youth & Culture", "Social Impact"], platform: "Web / Social", minCpmINR: 70, maxCpmINR: 150, trafficTier: "Mid-Tier Premium (10M-50M)" },
  { id: 176, name: "Aha OTT", niches: ["Regional Content", "General Entertainment"], platform: "OTT / Connected TV", minCpmINR: 90, maxCpmINR: 220, trafficTier: "Mid-Tier Premium (10M-50M)" },
  { id: 177, name: "Hoichoi TV", niches: ["Regional Content", "General Entertainment"], platform: "OTT / Connected TV", minCpmINR: 85, maxCpmINR: 200, trafficTier: "Mid-Tier Premium (10M-50M)" },
  { id: 178, name: "Sun NXT", niches: ["Regional Content", "General Entertainment"], platform: "OTT / Connected TV", minCpmINR: 80, maxCpmINR: 190, trafficTier: "Mass Market (50M+)" },
  { id: 179, name: "MX Player Network", niches: ["OTT", "General Entertainment"], platform: "Mobile App / Connected TV", minCpmINR: 60, maxCpmINR: 140, trafficTier: "Mass Market (50M+)" },
  { id: 180, name: "Josh Short Video App", niches: ["Regional Content", "Entertainment"], platform: "Mobile App", minCpmINR: 45, maxCpmINR: 100, trafficTier: "Mass Market (50M+)" },
  { id: 181, name: "Chingari Short Video Network", niches: ["Entertainment", "Crypto & Web3"], platform: "Mobile App", minCpmINR: 40, maxCpmINR: 95, trafficTier: "Mass Market (50M+)" },
  { id: 182, name: "Pocket FM", niches: ["Audio", "Audio Series"], platform: "Mobile App", minCpmINR: 70, maxCpmINR: 160, trafficTier: "Mass Market (50M+)" },
  { id: 183, name: "Kukufm Ads", niches: ["Audio", "Education & Audiobooks"], platform: "Mobile App", minCpmINR: 65, maxCpmINR: 150, trafficTier: "Mass Market (50M+)" },
  { id: 184, name: "Stage App (Regional OTT)", niches: ["Regional Content", "Entertainment"], platform: "Mobile App / OTT", minCpmINR: 55, maxCpmINR: 125, trafficTier: "Mid-Tier Premium (10M-50M)" },
  { id: 185, name: "ULCA / Chaupal OTT", niches: ["Regional Content", "General Entertainment"], platform: "OTT / Mobile App", minCpmINR: 60, maxCpmINR: 130, trafficTier: "Niche Focused (<10M)" },
  { id: 186, name: "Vijay Karnataka", niches: ["News", "Regional Content"], platform: "Web / App / Print", minCpmINR: 40, maxCpmINR: 95, trafficTier: "Mass Market (50M+)" },
  { id: 187, name: "Maharashtra Times", niches: ["News", "Regional Content"], platform: "Web / App / Print", minCpmINR: 45, maxCpmINR: 100, trafficTier: "Mass Market (50M+)" },
  { id: 188, name: "Pudhari Digital", niches: ["News", "Regional Content"], platform: "Web / Print", minCpmINR: 35, maxCpmINR: 85, trafficTier: "Mid-Tier Premium (10M-50M)" },
  { id: 189, name: "Sakal Media Group", niches: ["News", "Regional Content"], platform: "Web / App / Print", minCpmINR: 45, maxCpmINR: 105, trafficTier: "Mass Market (50M+)" },
  { id: 190, name: "Sambad Digital (Odisha)", niches: ["News", "Regional Content"], platform: "Web / App / Print", minCpmINR: 35, maxCpmINR: 80, trafficTier: "Mid-Tier Premium (10M-50M)" },
  { id: 191, name: "Prameya News", niches: ["News", "Regional Content"], platform: "Web / TV", minCpmINR: 30, maxCpmINR: 75, trafficTier: "Mid-Tier Premium (10M-50M)" },
  { id: 192, name: "Asamiya Pratidin", niches: ["News", "Regional Content"], platform: "Web / Print", minCpmINR: 35, maxCpmINR: 80, trafficTier: "Mid-Tier Premium (10M-50M)" },
  { id: 193, name: "Pratidin Time", niches: ["News", "Regional Content"], platform: "Web / TV Network", minCpmINR: 35, maxCpmINR: 85, trafficTier: "Mid-Tier Premium (10M-50M)" },
  { id: 194, name: "NorthEast Today", niches: ["News", "Regional Content"], platform: "Web / Desktop", minCpmINR: 40, maxCpmINR: 90, trafficTier: "Niche Focused (<10M)" },
  { id: 195, name: "Kashmir Monitor / Greater Kashmir", niches: ["News", "Regional Content"], platform: "Web / Print", minCpmINR: 35, maxCpmINR: 80, trafficTier: "Niche Focused (<10M)" },
    { id: 196, name: "LinkedIn Ads India", niches: ["B2B", "Careers", "Business"], platform: "Web / App", minCpmINR: 350, maxCpmINR: 850, trafficTier: "Mass Market (50M+)" },
  { id: 197, name: "Reddit India Ads", niches: ["Tech", "Gaming", "Youth & Culture"], platform: "Web / Mobile App", minCpmINR: 120, maxCpmINR: 280, trafficTier: "Mid-Tier Premium (10M-50M)" },
  { id: 198, name: "Quora India Network", niches: ["Education", "Knowledge", "Tech"], platform: "Web / Mobile App", minCpmINR: 90, maxCpmINR: 210, trafficTier: "Mass Market (50M+)" },
  { id: 199, name: "Pinterest India Network", niches: ["Fashion", "Lifestyle", "Home Decor"], platform: "Mobile App / Web", minCpmINR: 110, maxCpmINR: 260, trafficTier: "Mid-Tier Premium (10M-50M)" },
  { id: 200, name: "Snapchat India Ads", niches: ["Youth & Culture", "Gen Z", "Lifestyle"], platform: "Mobile App", minCpmINR: 80, maxCpmINR: 190, trafficTier: "Mass Market (50M+)" },
  { id: 201, name: "X (formerly Twitter) India", niches: ["News", "Tech", "Politics"], platform: "Web / Mobile App", minCpmINR: 140, maxCpmINR: 320, trafficTier: "Mass Market (50M+)" },
  { id: 202, name: "Truecaller Ad Network", niches: ["Utility", "Mass Communication"], platform: "Mobile App", minCpmINR: 75, maxCpmINR: 180, trafficTier: "Mass Market (50M+)" },
  { id: 203, name: "InMobi Ad Network", niches: ["In-App", "Gaming", "Utility"], platform: "Mobile App Network", minCpmINR: 50, maxCpmINR: 130, trafficTier: "Mass Market (50M+)" },
  { id: 204, name: "Unity Ads India", niches: ["Gaming", "In-App"], platform: "Mobile Games", minCpmINR: 60, maxCpmINR: 140, trafficTier: "Mass Market (50M+)" },
  { id: 205, name: "AppLovin Network India", niches: ["Gaming", "Casual Apps"], platform: "Mobile App", minCpmINR: 55, maxCpmINR: 135, trafficTier: "Mass Market (50M+)" },
  { id: 206, name: "Taboola India Network", niches: ["Native Ads", "News", "Content Recommendation"], platform: "Web / Mobile", minCpmINR: 40, maxCpmINR: 95, trafficTier: "Mass Market (50M+)" },
  { id: 207, name: "Outbrain India Network", niches: ["Native Ads", "Publishers"], platform: "Web / Mobile", minCpmINR: 45, maxCpmINR: 100, trafficTier: "Mass Market (50M+)" },
  { id: 208, name: "Spotify India Ads", niches: ["Audio", "Music", "Podcasts"], platform: "Mobile App / Web", minCpmINR: 120, maxCpmINR: 280, trafficTier: "Mass Market (50M+)" },
  { id: 209, name: "Amazon DSP India", niches: ["E-commerce", "Shopping", "OTT"], platform: "Web / App / FireTV", minCpmINR: 160, maxCpmINR: 380, trafficTier: "Mass Market (50M+)" },
  { id: 210, name: "Flipkart Ads (Commerce Media)", niches: ["E-commerce", "Shopping"], platform: "Mobile App / Web", minCpmINR: 140, maxCpmINR: 320, trafficTier: "Mass Market (50M+)" },
  { id: 211, name: "Myntra Ad Network", niches: ["Fashion", "Beauty", "Lifestyle"], platform: "Mobile App", minCpmINR: 150, maxCpmINR: 340, trafficTier: "Mass Market (50M+)" },
  { id: 212, name: "Nykaa Media Network", niches: ["Beauty", "Fashion", "Personal Care"], platform: "Mobile App / Web", minCpmINR: 160, maxCpmINR: 350, trafficTier: "Mid-Tier Premium (10M-50M)" },
  { id: 213, name: "Tata Neu Ads Network", niches: ["E-commerce", "Travel", "Fintech"], platform: "Mobile App", minCpmINR: 130, maxCpmINR: 300, trafficTier: "Mass Market (50M+)" },
  { id: 214, name: "Zomato In-App Media", niches: ["Food & Dining", "Hyperlocal"], platform: "Mobile App", minCpmINR: 140, maxCpmINR: 320, trafficTier: "Mass Market (50M+)" },
  { id: 215, name: "Swiggy Ads Network", niches: ["Food & Grocery", "Hyperlocal"], platform: "Mobile App", minCpmINR: 135, maxCpmINR: 310, trafficTier: "Mass Market (50M+)" },
  { id: 216, name: "Blinkit Ads", niches: ["Quick Commerce", "Grocery"], platform: "Mobile App", minCpmINR: 150, maxCpmINR: 330, trafficTier: "Mass Market (50M+)" },
  { id: 217, name: "Zepto Ads", niches: ["Quick Commerce", "Grocery"], platform: "Mobile App", minCpmINR: 145, maxCpmINR: 320, trafficTier: "Mid-Tier Premium (10M-50M)" },
  { id: 218, name: "Instamart (Swiggy) Ads", niches: ["Quick Commerce", "FMCG"], platform: "Mobile App", minCpmINR: 140, maxCpmINR: 310, trafficTier: "Mass Market (50M+)" },
  { id: 219, name: "BigBasket Advertising", niches: ["Grocery", "FMCG"], platform: "Mobile App / Web", minCpmINR: 130, maxCpmINR: 290, trafficTier: "Mass Market (50M+)" },
  { id: 220, name: "Uber India In-App Ads", niches: ["Mobility", "Travel", "Urban"], platform: "Mobile App", minCpmINR: 160, maxCpmINR: 360, trafficTier: "Mass Market (50M+)" },
  { id: 221, name: "Ola Cabs Media Network", niches: ["Mobility", "Travel"], platform: "Mobile App / In-Cab Screens", minCpmINR: 140, maxCpmINR: 320, trafficTier: "Mass Market (50M+)" },
  { id: 222, name: "Rapido Ads", niches: ["Mobility", "Youth & Daily Commute"], platform: "Mobile App", minCpmINR: 90, maxCpmINR: 210, trafficTier: "Mass Market (50M+)" },
  { id: 223, name: "Namma Yatri Network", niches: ["Mobility", "Regional Transit"], platform: "Mobile App", minCpmINR: 70, maxCpmINR: 160, trafficTier: "Mid-Tier Premium (10M-50M)" },
  { id: 224, name: "Urban Company Ads", niches: ["Home Services", "Lifestyle"], platform: "Mobile App", minCpmINR: 160, maxCpmINR: 350, trafficTier: "Mid-Tier Premium (10M-50M)" },
  { id: 225, name: "Porter Ads", niches: ["Logistics", "B2B & SMB"], platform: "Mobile App", minCpmINR: 100, maxCpmINR: 230, trafficTier: "Mid-Tier Premium (10M-50M)" },
  { id: 226, name: "Dunzo Ad Network", niches: ["Quick Commerce", "Hyperlocal"], platform: "Mobile App", minCpmINR: 110, maxCpmINR: 250, trafficTier: "Mid-Tier Premium (10M-50M)" },
  { id: 227, name: "PharmEasy Network", niches: ["Healthcare", "Pharma"], platform: "Mobile App / Web", minCpmINR: 130, maxCpmINR: 290, trafficTier: "Mid-Tier Premium (10M-50M)" },
  { id: 228, name: "Apollo 24|7 Media", niches: ["Healthcare", "Wellness"], platform: "Mobile App / Web", minCpmINR: 140, maxCpmINR: 310, trafficTier: "Mid-Tier Premium (10M-50M)" },
  { id: 229, name: "TATA 1mg Media", niches: ["Healthcare", "Wellness"], platform: "Mobile App / Web", minCpmINR: 135, maxCpmINR: 300, trafficTier: "Mid-Tier Premium (10M-50M)" },
  { id: 230, name: "Truemeds Advertising", niches: ["Healthcare", "Regional Audience"], platform: "Mobile App", minCpmINR: 90, maxCpmINR: 210, trafficTier: "Mid-Tier Premium (10M-50M)" },
  { id: 231, name: "RedBus Ad Network", niches: ["Travel", "Bus Transit"], platform: "Mobile App / Web", minCpmINR: 110, maxCpmINR: 250, trafficTier: "Mass Market (50M+)" },
  { id: 232, name: "ConfirmTkt Network", niches: ["Travel", "Rail Transit"], platform: "Mobile App", minCpmINR: 85, maxCpmINR: 190, trafficTier: "Mass Market (50M+)" },
  { id: 233, name: "Where Is My Train (Google)", niches: ["Travel", "Utility", "Transit"], platform: "Mobile App", minCpmINR: 60, maxCpmINR: 140, trafficTier: "Mass Market (50M+)" },
  { id: 234, name: "IndiGo Airlines Digital Media", niches: ["Travel", "Aviation & Premium"], platform: "Web / Mobile App / WiFi Portal", minCpmINR: 220, maxCpmINR: 500, trafficTier: "Mid-Tier Premium (10M-50M)" },
  { id: 235, name: "EaseMyTrip Ads", niches: ["Travel", "Ticketing"], platform: "Mobile App / Web", minCpmINR: 120, maxCpmINR: 270, trafficTier: "Mid-Tier Premium (10M-50M)" },
  { id: 236, name: "Team-BHP", niches: ["Automotive", "Enthusiasts"], platform: "Web Forum / Desktop", minCpmINR: 180, maxCpmINR: 400, trafficTier: "Niche Focused (<10M)" },
  { id: 237, name: "MotorBeam", niches: ["Automotive", "Bikes & Cars"], platform: "Web / YouTube Network", minCpmINR: 90, maxCpmINR: 200, trafficTier: "Niche Focused (<10M)" },
  { id: 238, name: "DriveSpark", niches: ["Automotive", "Regional Content"], platform: "Web / Mobile", minCpmINR: 70, maxCpmINR: 160, trafficTier: "Mid-Tier Premium (10M-50M)" },
  { id: 239, name: "BikeWale", niches: ["Automotive", "Two Wheelers"], platform: "Web / Mobile App", minCpmINR: 95, maxCpmINR: 210, trafficTier: "Mid-Tier Premium (10M-50M)" },
  { id: 240, name: "LBB (Little Black Book)", niches: ["Lifestyle", "Local Discovery", "Food"], platform: "Web / Mobile App", minCpmINR: 120, maxCpmINR: 280, trafficTier: "Niche Focused (<10M)" },
  { id: 241, name: "WhatShot", niches: ["Lifestyle", "Events", "Dining"], platform: "Web / Mobile App", minCpmINR: 100, maxCpmINR: 230, trafficTier: "Niche Focused (<10M)" },
  { id: 242, name: "Dineout (Swiggy Network)", niches: ["Dining", "Food & Lifestyle"], platform: "Mobile App", minCpmINR: 130, maxCpmINR: 290, trafficTier: "Mid-Tier Premium (10M-50M)" },
  { id: 243, name: "Magicpin Ads", niches: ["Hyperlocal", "Shopping & Rewards"], platform: "Mobile App", minCpmINR: 95, maxCpmINR: 210, trafficTier: "Mass Market (50M+)" },
  { id: 244, name: "CRED Pay & Media Network", niches: ["Fintech", "High Net Worth / Premium"], platform: "Mobile App", minCpmINR: 300, maxCpmINR: 700, trafficTier: "Mid-Tier Premium (10M-50M)" },
  { id: 245, name: "Indmoney Ads", niches: ["Finance", "US Stocks & Wealth"], platform: "Mobile App", minCpmINR: 180, maxCpmINR: 400, trafficTier: "Mid-Tier Premium (10M-50M)" },
  { id: 246, name: "ET Money Network", niches: ["Finance", "Mutual Funds"], platform: "Mobile App / Web", minCpmINR: 160, maxCpmINR: 350, trafficTier: "Mid-Tier Premium (10M-50M)" },
  { id: 247, name: "PolicyBazaar Network", niches: ["Insurance", "Finance"], platform: "Web / Mobile App", minCpmINR: 170, maxCpmINR: 380, trafficTier: "Mass Market (50M+)" },
  { id: 248, name: "BankBazaar", niches: ["Finance", "Credit Cards & Loans"], platform: "Web / Mobile App", minCpmINR: 150, maxCpmINR: 340, trafficTier: "Mid-Tier Premium (10M-50M)" },
  { id: 249, name: "Paisabazaar Network", niches: ["Finance", "Credit Scores"], platform: "Web / Mobile App", minCpmINR: 140, maxCpmINR: 320, trafficTier: "Mass Market (50M+)" },
  { id: 250, name: "Tally Solutions Network", niches: ["B2B", "SMB & Accounting"], platform: "Software / Web", minCpmINR: 250, maxCpmINR: 600, trafficTier: "Niche Focused (<10M)" },
  { id: 251, name: "Khatabook Network", niches: ["Fintech", "SMB & Merchants"], platform: "Mobile App", minCpmINR: 80, maxCpmINR: 180, trafficTier: "Mass Market (50M+)" },
  { id: 252, name: "OkCredit Network", niches: ["Fintech", "SMB & Merchants"], platform: "Mobile App", minCpmINR: 75, maxCpmINR: 170, trafficTier: "Mid-Tier Premium (10M-50M)" },
  { id: 253, name: "IndiaMART B2B Ads", niches: ["B2B", "Manufacturing & Wholesale"], platform: "Web / Mobile App", minCpmINR: 180, maxCpmINR: 420, trafficTier: "Mass Market (50M+)" },
  { id: 254, name: "TradeIndia", niches: ["B2B", "Industrial & Trade"], platform: "Web / Mobile", minCpmINR: 150, maxCpmINR: 350, trafficTier: "Mid-Tier Premium (10M-50M)" },
  { id: 255, name: "Justdial Ads", niches: ["Local Search", "B2B & B2C"], platform: "Web / Mobile App", minCpmINR: 110, maxCpmINR: 250, trafficTier: "Mass Market (50M+)" },
  { id: 256, name: "Sulekha Network", niches: ["Local Services", "Education"], platform: "Web / Mobile", minCpmINR: 90, maxCpmINR: 210, trafficTier: "Mid-Tier Premium (10M-50M)" },
  { id: 257, name: "Naukri.com Media", niches: ["Careers", "Jobs & Corporate"], platform: "Web / Mobile App", minCpmINR: 200, maxCpmINR: 450, trafficTier: "Mass Market (50M+)" },
  { id: 258, name: "Foundit (formerly Monster India)", niches: ["Careers", "Jobs"], platform: "Web / Mobile App", minCpmINR: 140, maxCpmINR: 310, trafficTier: "Mid-Tier Premium (10M-50M)" },
  { id: 259, name: "Shine.com", niches: ["Careers", "Jobs"], platform: "Web / Mobile App", minCpmINR: 120, maxCpmINR: 280, trafficTier: "Mid-Tier Premium (10M-50M)" },
  { id: 260, name: "AmbitionBox", niches: ["Careers", "Company Reviews"], platform: "Web / Mobile", minCpmINR: 130, maxCpmINR: 290, trafficTier: "Mid-Tier Premium (10M-50M)" },
  { id: 261, name: "Glassdoor India", niches: ["Careers", "Corporate & Salaries"], platform: "Web / App", minCpmINR: 210, maxCpmINR: 480, trafficTier: "Mid-Tier Premium (10M-50M)" },
  { id: 262, name: "Unstop (formerly Dare2Compete)", niches: ["Education", "Students & Competitions"], platform: "Web / Mobile App", minCpmINR: 110, maxCpmINR: 250, trafficTier: "Mid-Tier Premium (10M-50M)" },
  { id: 263, name: "Internshala Ads Network", niches: ["Education", "Internships & Students"], platform: "Web / Mobile App", minCpmINR: 100, maxCpmINR: 230, trafficTier: "Mid-Tier Premium (10M-50M)" },
  { id: 264, name: "PhysicsWallah App Network", niches: ["Education", "Competitive Exams"], platform: "Mobile App / Web", minCpmINR: 85, maxCpmINR: 190, trafficTier: "Mass Market (50M+)" },
  { id: 265, name: "Unacademy Network", niches: ["Education", "E-learning"], platform: "Mobile App / Web", minCpmINR: 95, maxCpmINR: 210, trafficTier: "Mass Market (50M+)" },
  { id: 266, name: "Way2News", niches: ["Regional Content", "Short News"], platform: "Mobile App", minCpmINR: 50, maxCpmINR: 115, trafficTier: "Mass Market (50M+)" },
  { id: 267, name: "Public App (InShorts Group)", niches: ["Regional Content", "Hyperlocal News"], platform: "Mobile App", minCpmINR: 45, maxCpmINR: 105, trafficTier: "Mass Market (50M+)" },
  { id: 268, name: "Khabar Lahariya", niches: ["Regional Content", "Grassroots News"], platform: "Web / YouTube", minCpmINR: 40, maxCpmINR: 90, trafficTier: "Niche Focused (<10M)" },
  { id: 269, name: "EastMojo", niches: ["Regional Content", "NorthEast News"], platform: "Web / Mobile", minCpmINR: 40, maxCpmINR: 95, trafficTier: "Niche Focused (<10M)" },
  { id: 270, name: "V6 News Digital", niches: ["Regional Content", "Telugu News"], platform: "Web / App / TV", minCpmINR: 35, maxCpmINR: 85, trafficTier: "Mid-Tier Premium (10M-50M)" },
  { id: 271, name: "TV9 Digital Network", niches: ["News", "Regional Content"], platform: "Web / App / YouTube", minCpmINR: 50, maxCpmINR: 115, trafficTier: "Mass Market (50M+)" },
  { id: 272, name: "Suvarna News Digital", niches: ["News", "Kannada Content"], platform: "Web / TV Network", minCpmINR: 40, maxCpmINR: 95, trafficTier: "Mid-Tier Premium (10M-50M)" },
  { id: 273, name: "Thanthi TV / Daily Thanthi", niches: ["News", "Tamil Content"], platform: "Web / App / Print", minCpmINR: 45, maxCpmINR: 105, trafficTier: "Mass Market (50M+)" },
  { id: 274, name: "Polimer News Digital", niches: ["News", "Tamil Content"], platform: "Web / YouTube Network", minCpmINR: 35, maxCpmINR: 85, trafficTier: "Mid-Tier Premium (10M-50M)" },
  { id: 275, name: "Asianet News Digital", niches: ["News", "Malayalam & South"], platform: "Web / App Network", minCpmINR: 55, maxCpmINR: 125, trafficTier: "Mass Market (50M+)" },
  { id: 276, name: "24 News Digital (Flowers TV)", niches: ["News", "Malayalam Content"], platform: "Web / App", minCpmINR: 45, maxCpmINR: 100, trafficTier: "Mid-Tier Premium (10M-50M)" },
  { id: 277, name: "Sandesh Digital", niches: ["News", "Gujarati Content"], platform: "Web / App / Print", minCpmINR: 40, maxCpmINR: 90, trafficTier: "Mid-Tier Premium (10M-50M)" },
  { id: 278, name: "Gujarat Samachar Digital", niches: ["News", "Gujarati Content"], platform: "Web / App / Print", minCpmINR: 40, maxCpmINR: 95, trafficTier: "Mass Market (50M+)" },
  { id: 279, name: "Punjab Kesari Digital", niches: ["News", "Hindi & Punjabi"], platform: "Web / App / Print", minCpmINR: 40, maxCpmINR: 90, trafficTier: "Mass Market (50M+)" },
  { id: 280, name: "Jagran Josh", niches: ["Education", "General Knowledge"], platform: "Web / Mobile", minCpmINR: 50, maxCpmINR: 110, trafficTier: "Mass Market (50M+)" },
  { id: 281, name: "Careers360", niches: ["Education", "College Admissions"], platform: "Web / Mobile", minCpmINR: 80, maxCpmINR: 175, trafficTier: "Mid-Tier Premium (10M-50M)" },
  { id: 282, name: "AglaSem", niches: ["Education", "Exams & Schools"], platform: "Web / Desktop", minCpmINR: 45, maxCpmINR: 100, trafficTier: "Mid-Tier Premium (10M-50M)" },
  { id: 283, name: "Indiagovernments / Testbook Govt", niches: ["Jobs", "Govt Exams"], platform: "Web / Mobile", minCpmINR: 35, maxCpmINR: 80, trafficTier: "Mass Market (50M+)" },
  { id: 284, name: "AstroSage Network", niches: ["Astrology", "Lifestyle"], platform: "Web / Mobile App", minCpmINR: 60, maxCpmINR: 140, trafficTier: "Mass Market (50M+)" },
  { id: 285, name: "Astrotalk In-App Ads", niches: ["Astrology", "Lifestyle"], platform: "Mobile App", minCpmINR: 110, maxCpmINR: 260, trafficTier: "Mid-Tier Premium (10M-50M)" },
  { id: 286, name: "Prokerala", niches: ["Astrology", "News", "Utility"], platform: "Web / Mobile", minCpmINR: 45, maxCpmINR: 100, trafficTier: "Mid-Tier Premium (10M-50M)" },
  { id: 287, name: "Drik Panchang", niches: ["Astrology", "Culture & Calendar"], platform: "Web / Mobile App", minCpmINR: 50, maxCpmINR: 110, trafficTier: "Mass Market (50M+)" },
  { id: 288, name: "MyGate App Network", niches: ["Community", "Gated Communities & Premium"], platform: "Mobile App", minCpmINR: 200, maxCpmINR: 480, trafficTier: "Mid-Tier Premium (10M-50M)" },
  { id: 289, name: "NoBrokerhood Network", niches: ["Community", "Gated Communities"], platform: "Mobile App", minCpmINR: 180, maxCpmINR: 420, trafficTier: "Mid-Tier Premium (10M-50M)" },
  { id: 290, name: "Park+ Ads", niches: ["Automotive", "Parking & Fastag"], platform: "Mobile App", minCpmINR: 150, maxCpmINR: 340, trafficTier: "Mid-Tier Premium (10M-50M)" },
  { id: 291, name: "CarInfo App", niches: ["Automotive", "Vehicle Info & Insurance"], platform: "Mobile App", minCpmINR: 90, maxCpmINR: 210, trafficTier: "Mass Market (50M+)" },
  { id: 292, name: "mParivahan Ads", niches: ["Utility", "Government & Transport"], platform: "Mobile App", minCpmINR: 40, maxCpmINR: 85, trafficTier: "Mass Market (50M+)" },
  { id: 293, name: "DigiLocker In-App Banner Network", niches: ["Utility", "Government"], platform: "Mobile App", minCpmINR: 50, maxCpmINR: 105, trafficTier: "Mass Market (50M+)" },
  { id: 294, name: "Speedtest by Ookla (India Tier)", niches: ["Utility", "Tech & Telecom"], platform: "Mobile App / Web", minCpmINR: 120, maxCpmINR: 280, trafficTier: "Mass Market (50M+)" },
  { id: 295, name: "CamScanner / Adobe Scan India Network", niches: ["Utility", "Productivity"], platform: "Mobile App", minCpmINR: 110, maxCpmINR: 250, trafficTier: "Mass Market (50M+)" }
]
