const publishers = [
    { 
        id: 0,
        name: "JioHotstar Sports", 
        niches: ["Sports", "Live Streaming"], 
        platform: "OTT / Connected TV", 
        minCpmINR: 90,
        maxCpmINR: 240,
        trafficTier: "Mass Market (50M+)",
        formats: ["Video Pre-Roll", "Video Mid-Roll", "Connected TV Banner"],
        portal: "https://magnite.com",
        channels: ["Star Sports 1 (HD/SD)", "Star Sports Select", "Star Gold", "JioCinema Regional Feeds"],
        sports: ["IPL Cricket", "ICC Tournaments", "English Premier League (EPL)", "Pro Kabaddi League"]
    },
    { 
        id: 1,
        name: "Cricbuzz", 
        niches: ["Sports"], 
        platform: "Mobile App / Web", 
        minCpmINR: 65,
        maxCpmINR: 125,
        trafficTier: "Mass Market (50M+)",
        formats: ["Banner Displays", "Audio Ads"],
        portal: "https://google.com",
        channels: ["Cricbuzz Live (Video Feed)", "Cricbuzz Comm Box (Audio)", "Regional Language Sub-pages"],
        sports: ["Domestic T20 Leagues", "Test Match Coverages", "ICC Women's World Cup"]
    },
    { 
        id: 2,
        name: "InShorts", 
        niches: ["News"], 
        platform: "Mobile App", 
        minCpmINR: 80,
        maxCpmINR: 180,
        trafficTier: "Mid-Tier Premium (10M-50M)",
        formats: ["Native In-Feed", "Banner Displays"],
        portal: "https://inshorts.com",
        channels: ["National Ticker Feed", "Tech Short Bites", "Business Pulse Channel"],
        sports: ["General Sports Highlights", "Olympic Daily Cards"]
    },
    { 
        id: 3,
        name: "Moneycontrol", 
        niches: ["Finance", "News"], 
        platform: "Web / Desktop", 
        minCpmINR: 150,
        maxCpmINR: 350,
        trafficTier: "Mid-Tier Premium (10M-50M)",
        formats: ["Native In-Feed", "Banner Displays"],
        portal: "https://moneycontrol.com",
        channels: ["MC Pro Premium", "CNBC-TV18 Live Stream Integration", "Commodities Desk Feed"],
        sports: ["IPL Brand Valuation News", "Sports Business & Finance Segment"]
    },
    { 
        id: 4,
        name: "Sportskeeda India", 
        niches: ["Sports", "Gaming"], 
        platform: "Web", 
        minCpmINR: 50,
        maxCpmINR: 110,
        trafficTier: "Mid-Tier Premium (10M-50M)",
        formats: ["Banner Displays", "Native In-Feed"],
        portal: "https://sportskeeda.com",
        channels: ["SK Wrestling Channel", "SK Esports Hub", "Cricket Analytics Desk"],
        sports: ["WWE India", "Free Fire / BGMI Esports", "Indian Football (ISL)", "La Liga"]
    },
    { 
        id: 5,
        name: "Zee5 Premium Network", 
        niches: ["General Entertainment", "Regional Content"], 
        platform: "OTT / Connected TV", 
        minCpmINR: 85,
        maxCpmINR: 210,
        trafficTier: "Mass Market (50M+)",
        formats: ["Video Pre-Roll", "Video Mid-Roll"],
        portal: "https://zee5.com",
        channels: ["Zee TV HD", "Zee Cinema", "Zee Café", "Regional Entertainment Bundles"],
        sports: ["Daily Soap Mega-Sponsorships", "Reality Show Mid-Rolls", "Regional Web-Series Placements"]
    },
    { 
        id: 6,
        name: "MX Player", 
        niches: ["General Entertainment", "Regional Content"], 
        platform: "Mobile App / Web", 
        minCpmINR: 45,
        maxCpmINR: 95,
        trafficTier: "Mass Market (50M+)",
        formats: ["Video Pre-Roll", "Video Mid-Roll", "Banner Displays"],
        portal: "https://mxplayer.in",
        channels: ["MX Original Feeds", "Vdesi (International Dubbed)", "Short Video Tickers"],
        sports: ["Web Series Video Interstitials", "Masthead Video Placements"]
    },
    { 
        id: 7,
        name: "Aha (Ahha)", 
        niches: ["Regional Content", "General Entertainment"], 
        platform: "OTT / Connected TV", 
        minCpmINR: 110,
        maxCpmINR: 260,
        trafficTier: "Niche Focused (<10M)",
        formats: ["Video Pre-Roll", "Video Mid-Roll"],
        portal: "https://aha.video",
        channels: ["Aha Telugu Live", "Aha Tamil Live", "Aha Kids corner"],
        sports: ["Regional Movie Launch Sponsorships", "Vernacular Mid-Roll Video"]
    },
    { 
        id: 8,
        name: "Amazon Prime Video", 
        niches: ["General Entertainment"], 
        platform: "OTT / Connected TV", 
        minCpmINR: 250,
        maxCpmINR: 450,
        trafficTier: "Mass Market (50M+)",
        formats: ["Video Pre-Roll", "Connected TV Banner"],
        portal: "https://amazon.com",
        channels: ["Prime Video Ad-Supported Tier", "Live Sports Broadcast Bundles"],
        sports: ["Global Live Matches", "Premium Series Pre-Rolls", "Connected TV Banner Placements"]
    },
    { 
        id: 9,
        name: "Hoichoi OTT", 
        niches: ["Regional Content", "General Entertainment"], 
        platform: "Mobile App / Web", 
        minCpmINR: 60,
        maxCpmINR: 130,
        trafficTier: "Niche Focused (<10M)",
        formats: ["Video Pre-Roll", "Banner Displays"],
        portal: "https://hoichoi.tv",
        channels: ["Bengali Originals Feed", "Hoichoi World Desk"],
        sports: ["Regional Bengali Web-Series Sponsorships", "Native UI Display In-App"]
    },
    { 
        id: 10,
        name: "Kuku TV", 
        niches: ["Regional Content", "General Entertainment"], 
        platform: "Mobile App", 
        minCpmINR: 35,
        maxCpmINR: 75,
        trafficTier: "Mid-Tier Premium (10M-50M)",
        formats: ["Audio Ads"],
        portal: "https://kukufm.com",
        channels: ["Short Audio-Serial Feeds", "Regional Story Channels"],
        sports: ["Audio In-Stream Sponsorships", "In-App Home Banner Placements"]
    },
    { 
        id: 11,
        name: "Hungama OTT", 
        niches: ["General Entertainment"], 
        platform: "Mobile App / Web", 
        minCpmINR: 40,
        maxCpmINR: 85,
        trafficTier: "Mid-Tier Premium (10M-50M)",
        formats: ["Audio Ads", "Video Mid-Roll"],
        portal: "https://hungama.com",
        channels: ["Hungama Music Stream", "Hungama Play Video Node"],
        sports: ["In-Audio Commercial Clips", "Video Mid-Roll Interstitials"]
    },
    { 
        id: 12,
        name: "Sony LIV", 
        niches: ["Sports", "General Entertainment"], 
        platform: "OTT / Connected TV", 
        minCpmINR: 120,
        maxCpmINR: 290,
        trafficTier: "Mass Market (50M+)",
        formats: ["Video Pre-Roll", "Video Mid-Roll", "Connected TV Banner"],
        portal: "https://sonyliv.com",
        channels: ["Sony LIV Sports HD", "Sony SAB Entertainment", "Sony SET National Feed"],
        sports: ["UEFA Champions League", "Cricket Bilateral Series", "Olympic Games", "WWE Premium Events"]
    },
    { 
        id: 13,
        name: "Ratri App", 
        niches: ["General Entertainment"], 
        platform: "Mobile App", 
        minCpmINR: 30,
        maxCpmINR: 65,
        trafficTier: "Niche Focused (<10M)",
        formats: ["Video Mid-Roll", "Banner Displays"],
        portal: "https://google.com",
        channels: ["Short Story Video Streams", "Adult Romance Nodes"],
        sports: ["In-Feed Mobile Video Ads", "Standard Display Interstitials"]
    },
    { 
        id: 14,
        name: "ShemarooME", 
        niches: ["General Entertainment", "Regional Content"], 
        platform: "OTT / Connected TV", 
        minCpmINR: 50,
        maxCpmINR: 120,
        trafficTier: "Mid-Tier Premium (10M-50M)",
        formats: ["Video Pre-Roll", "Connected TV Banner"],
        portal: "https://shemaroome.com",
        channels: ["Shemaroo Classic TV", "Gujarati Specialty Node", "Bhojpuri Cinema Feed"],
        sports: ["Classic Bollywood Content Wrappers", "Live Regional Broadcast Banners"]
    },
    { 
        id: 15,
        name: "Aaj Tak (aajtak.in)", 
        niches: ["News", "Live Streaming"], 
        platform: "Mobile App / Web", 
        minCpmINR: 60,
        maxCpmINR: 115,
        trafficTier: "Mass Market (50M+)",
        formats: ["Video Pre-Roll", "Video Mid-Roll", "Banner Displays"],
        portal: "https://aajtak.in",
        channels: ["Aaj Tak Live TV Stream", "Good News Today Hub", "Aaj Tak Bangla Regional Feeds"],
        sports: ["Live Debate L-Band Video Overlays", "Breaking News Push Notification Sponsorships"]
    },
    { 
        id: 16,
        name: "Netflix India", 
        niches: ["General Entertainment"], 
        platform: "OTT / Connected TV", 
        minCpmINR: 300,
        maxCpmINR: 550,
        trafficTier: "Mass Market (50M+)",
        formats: ["Video Pre-Roll"],
        portal: "https://netflix.com",
        channels: ["Netflix Standard with Ads Tier", "Top 10 Global Content Nodes"],
        sports: ["Live Exhibition Events", "Premium Series Pre-Rolls", "Unskippable Video Blocks"]
    },
    { 
        id: 17,
        name: "Jio TV", 
        niches: ["Live Streaming", "General Entertainment"], 
        platform: "Mobile App", 
        minCpmINR: 45,
        maxCpmINR: 90,
        trafficTier: "Mass Market (50M+)",
        formats: ["Video Pre-Roll", "Banner Displays"],
        portal: "https://magnite.com",
        channels: ["800+ Live Broadcast TV Channels", "Jio Darshan Feeds", "Jio Regional News Layouts"],
        sports: ["Simulcast Live Match Overlays", "Channel Switching Splash Video Ads"]
    },
    { 
        id: 18,
        name: "Spotify India", 
        niches: ["General Entertainment"], 
        platform: "Mobile App", 
        minCpmINR: 120,
        maxCpmINR: 220,
        trafficTier: "Mass Market (50M+)",
        formats: ["Audio Ads", "Video Pre-Roll"],
        portal: "https://spotify.com",
        channels: ["Spotify Free Audio Track Node", "Top Indian Podcasts Panel", "Spotify Video Takeover Link"],
        sports: ["Audio Ad Breaks (15-30s)", "Sponsored Playlist Takeovers", "Podcast Host-Read Sponsorships"]},
        {id: 19,name: "JioSaavn",niches: ["General Entertainment", "Regional Content"],platform: "Mobile App",minCpmINR: 70,maxCpmINR: 140,trafficTier: "Mid-Tier Premium (10M-50M)",formats: ["Audio Ads", "Banner Displays"],portal: "jiosaavn.com",channels: ["Saavn Free Audio Layer", "Regional Artist Showcases"],sports: ["In-Stream Audio Commercial Spots", "Interactive Mobile Audio Display Banners"]},{id: 20,name: "Times of India (indiatimes.com)",niches: ["News"],platform: "Web / App",minCpmINR: 75,maxCpmINR: 160,trafficTier: "Mass Market (50M+)",formats: ["Native In-Feed", "Banner Displays"],portal: "https://colombiaonline.com",channels: ["TOI Plus Premium Feed", "City-Specific Hyperlocal Feeds", "Gadgets Now Section"],sports: ["National News Banners", "Native In-Feed Sponsored Content Pieces"]},{id: 21,name: "NDTV (ndtv.com)",niches: ["News", "Live Streaming"],platform: "Web / App",minCpmINR: 85,maxCpmINR: 190,trafficTier: "Mid-Tier Premium (10M-50M)",formats: ["Video Pre-Roll", "Banner Displays"],portal: "ndtv.com",channels: ["NDTV 24x7 English Stream", "NDTV India Hindi Stream", "NDTV Profit Financial Node"],sports: ["Premium Homepage Masthead Video Takeovers", "In-Stream Video Pre-Roll Nodes"]},{id: 22,name: "Oneindia (oneindia.com)",niches: ["News", "Regional Content"],platform: "Web Only",minCpmINR: 35,maxCpmINR: 80,trafficTier: "Mid-Tier Premium (10M-50M)",formats: ["Native In-Feed", "Banner Displays"],portal: "oneindia.com",channels: ["Vernacular Hindi Feed", "Tamil/Telugu Core Desks", "Kannada/Malayalam Local Networks"],sports: ["Sticky Anchor Banners", "Native Outbrain Recommended Widget Placements"]},{id: 23,name: "News18 (news18.com)",niches: ["News", "Live Streaming"],platform: "Web / App",minCpmINR: 55,maxCpmINR: 130,trafficTier: "Mass Market (50M+)",formats: ["Video Pre-Roll", "Video Mid-Roll", "Banner Displays"],portal: "news18.com",channels: ["News18 Network National", "CNN-News18 Premium", "14+ Regional Indian Language Feeds"],sports: ["Live Stream Mid-Roll Ad Triggers", "Interstitials Mobile Popups"]},{id: 24,name: "India Today (indiatoday.in)",niches: ["News"],platform: "Web / App",minCpmINR: 90,maxCpmINR: 210,trafficTier: "Mid-Tier Premium (10M-50M)",formats: ["Video Pre-Roll", "Banner Displays", "Native In-Feed"],portal: "indiatoday.in",channels: ["India Today TV Live Feed", "Daily O Opinion Portal", "India Today Premium Magazine Node"],sports: ["Long-Form Editorial Sponsorship Panels", "High-Impact Video Outstream Blocks"]},{id: 25,name: "Hindustan Times (hindustantimes.com)",niches: ["News"],platform: "Web / App",minCpmINR: 70,maxCpmINR: 175,trafficTier: "Mass Market (50M+)",formats: ["Native In-Feed", "Banner Displays"],portal: "hindustantimes.com",channels: ["HT National Desk Feed", "HT Tech/Lifestyle Node", "HT Brunch Luxury Segment"],sports: ["Premium Smart-Card Content Placements", "Desktop Sidebar Sticky Banner Layouts"]},{id: 26,name: "The Hindu (thehindu.com)",niches: ["News"],platform: "Web / App",minCpmINR: 110,maxCpmINR: 250,trafficTier: "Mid-Tier Premium (10M-50M)",formats: ["Banner Displays", "Native In-Feed"],portal: "thehindu.com",channels: ["The Hindu Digital Premium", "BusinessLine Financial Nodes", "Frontline Analytical Magazine"],sports: ["Clean/Low-Clutter Premium Display Banners", "Educated/UPSC Demographics Target Filters"]},{id: 27,name: "Indian Express (indianexpress.com)",niches: ["News"],platform: "Web / App",minCpmINR: 80,maxCpmINR: 195,trafficTier: "Mid-Tier Premium (10M-50M)",formats: ["Native In-Feed", "Banner Displays"],portal: "https://indianexpress.com",channels: ["IE National Opinion Desk", "IE Express Explained Specialty Hub", "ieTamil / ieBangla Regional Nodes"],sports: ["In-Article Text Context Banner Matches", "Audio Podcast Sponsorship Audio Ads"]},{id: 28,name: "Dainik Bhaskar (bhaskar.com)",niches: ["News", "Regional Content"],platform: "Mobile App / Web",minCpmINR: 45,maxCpmINR: 105,trafficTier: "Mass Market (50M+)",formats: ["Native In-Feed", "Banner Displays"],portal: "dbcorp.in",channels: ["Dainik Bhaskar Hindi Main", "Divya Bhaskar Gujarati", "Divya Marathi Feed"],sports: ["App Splash/Welcome Interstitial Graphics", "Vernacular Regional In-Feed News Ads"]},{id: 29,name: "Jagran (jagran.com)",niches: ["News", "Regional Content"],platform: "Web / App",minCpmINR: 40,maxCpmINR: 95,trafficTier: "Mass Market (50M+)",formats: ["Native In-Feed", "Banner Displays"],portal: "jagran.com",channels: ["Dainik Jagran Core Hindi", "Jagran English Portal", "HerZindagi Women Lifestyle Segment"],sports: ["Standard Content Responsive Banner Sets", "Taboola Recommendation Ad Widgets"]},{id: 30,name: "Live Hindustan (livehindustan.com)",niches: ["News", "Regional Content"],platform: "Web Only",minCpmINR: 35,maxCpmINR: 85,trafficTier: "Mass Market (50M+)",formats: ["Native In-Feed", "Banner Displays"],portal: "livehindustan.com",channels: ["Hindi News Grid North India", "UP/Bihar Local District Channels"],sports: ["Native Dynamic Display Banner Blocks", "In-Article Outstream Autoplay Video Ads"]},{id: 31,name: "ABP Live (abplive.com)",niches: ["News", "Live Streaming"],platform: "Web / App",minCpmINR: 50,maxCpmINR: 120,trafficTier: "Mass Market (50M+)",formats: ["Video Pre-Roll", "Video Mid-Roll", "Banner Displays"],portal: "abplive.com",channels: ["ABP News Hindi Live", "ABP Ananda Bengali Feed", "ABP Majha Marathi News Stream"],sports: ["Live TV Side-Panel Dynamic Ads", "Mobile App Push-Sponsorship Trigger Slates"]},{id: 32,name: "Economic Times (economictimes.com)",niches: ["Finance", "News"],platform: "Web / Desktop",minCpmINR: 180,maxCpmINR: 400,trafficTier: "Mid-Tier Premium (10M-50M)",formats: ["Native In-Feed", "Banner Displays"],portal: "indiatimes.com",channels: ["ET Prime Premium Portal", "ET Markets Live Stock Ticker Hub", "Panache Luxury Lifestyle Segment"],sports: ["Corporate & B2B Target Overlay Panels", "High-Value Financial Demographic Takeovers"]},{id: 33,name: "Livemint (livemint.com)",niches: ["Finance", "News"],platform: "Web / Desktop",minCpmINR: 160,maxCpmINR: 380,trafficTier: "Mid-Tier Premium (10M-50M)",formats: ["Native In-Feed", "Banner Displays"],portal: "livemint.com",channels: ["Mint Premium Corporate Analytics", "Mint Lounge Culture Segments"],sports: ["Executive Tier Premium Display Placements", "In-Article Clean Native Sponsorship Links"]},{id: 34,name: "Zee News (india.com)",niches: ["News", "Live Streaming"],platform: "Web / App",minCpmINR: 50,maxCpmINR: 115,trafficTier: "Mass Market (50M+)",formats: ["Video Pre-Roll", "Video Mid-Roll", "Banner Displays"],portal: "india.com",channels: ["Zee News National Hindi Live", "Zee Business Finance News Feed", "Zee 24 Taas Regional Node"],sports: ["Streaming Pre-Roll Unskippable Ads", "Multi-Sidebar Programmatic Standard Banners"]},{id: 35,name: "DNA India (dnaindia.com)",niches: ["News"],platform: "Web Only",minCpmINR: 40,maxCpmINR: 90,trafficTier: "Mid-Tier Premium (10M-50M)",formats: ["Native In-Feed", "Banner Displays"],portal: "dnaindia.com",channels: ["DNA Originals Trending Node", "DNA Entertainment News Panel"],sports: ["Mid-Article Content Responsive Ads", "Native Context Link Recommendations"]},{id: 36,name: "Firstpost (firstpost.com)",niches: ["News"],platform: "Web Only",minCpmINR: 65,maxCpmINR: 140,trafficTier: "Mid-Tier Premium (10M-50M)",formats: ["Video Pre-Roll", "Native In-Feed", "Banner Displays"],portal: "firstpost.com",channels: ["Firstpost Global Show Video Node", "Firstpost Vantage Analytical Desk"],sports: ["Global Viewers Outstream Video Placements", "Premium Editorial Sponsorship Header Blocks"]},{id: 37,name: "Business Standard (business-standard.com)",niches: ["Finance", "News"],platform: "Web / Desktop",minCpmINR: 140,maxCpmINR: 320,trafficTier: "Mid-Tier Premium (10M-50M)",formats: ["Native In-Feed", "Banner Displays"],portal: "business-standard.com",channels: ["BS Premium Financial Analytics", "BS Corporate Strategy Columns"],sports: ["B2B Decision Makers Banner Filters", "Clean Text-Matched Advertising Ad-Units"]},{id: 38,name: "BBC News India (bbc.com)",niches: ["News", "International Network"],platform: "Web / App",minCpmINR: 150,maxCpmINR: 300,trafficTier: "Mid-Tier Premium (10M-50M)",formats: ["Video Pre-Roll", "Banner Displays"],portal: "bbc.com",channels: ["BBC World News Global Hub", "BBC Hindi / Tamil Language Desks", "BBC Marathi Analytical Node"],sports: ["Strict Brand-Safe Premium Banner Placements", "International Quality Outstream Video Blocks"]},  
        {
    id: 39,
    name: "FanCode", 
    niches: ["Sports", "Live Streaming"], 
    platform: "Mobile App / Web", 
    minCpmINR: 110,
    maxCpmINR: 260,
    trafficTier: "Mid-Tier Premium (10M-50M)",
    formats: ["Video Pre-Roll", "Video Mid-Roll", "Banner Displays"],
    portal: "https://fancode.com",
    channels: ["FanCode Live Main Feed", "Dream Sports Ad Exchange Node", "Regional Language Commentary Slates"],
    sports: ["Bilateral Cricket Tours", "Hero I-League", "Super Smash T20", "Caraba Cup", "Major League Cricket"]
},
{ 
    id: 40,
    name: "DAZN India", 
    niches: ["Sports", "International Network"], 
    platform: "OTT / Connected TV", 
    minCpmINR: 180,
    maxCpmINR: 420,
    trafficTier: "Niche Focused (<10M)",
    formats: ["Video Pre-Roll", "Connected TV Banner"],
    portal: "https://daznmedia.com",
    channels: ["DAZN Fight Channel", "DAZN Motorsport Stream Node", "Global Premium Soccer Feeds"],
    sports: ["Championship Boxing", "MMA Match Cards", "International Motorsports", "Premium European Football"]
},
{ 
    id: 41,
    name: "SportVot", 
    niches: ["Sports", "Regional Content"], 
    platform: "Mobile App / Web", 
    minCpmINR: 35,
    maxCpmINR: 75,
    trafficTier: "Niche Focused (<10M)",
    formats: ["Video Pre-Roll", "Banner Displays", "Native In-Feed"],
    portal: "https://sportvot.com",
    channels: ["State Tournament Streams", "District Sports Hub", "Grassroots Athlete Profiles Page"],
    sports: ["Local Kabaddi Leagues", "Corporate Cricket Cups", "State-Level Football Championships"]
},
{ 
    id: 42,
    name: "TV9 Marathi",
    niches: ["News", "Regional Content", "Live Streaming"],
    platform: "Web / App / TV",
    minCpmINR: 45,
    maxCpmINR: 110,
    trafficTier: "Mass Market (50M+)",
    formats: ["Video Pre-Roll", "Video Mid-Roll", "Banner Displays"],
    portal: "https://www.tv9marathi.com",
    channels: ["TV9 Marathi Live", "Maharashtra News", "Mumbai News", "Pune News"],
    sports: ["Marathi Sports News", "Cricket Coverage"]
},
{ 
    id: 43,
    name: "Zee 24 Taas",
    niches: ["News", "Regional Content", "Live Streaming"],
    platform: "Web / App / TV",
    minCpmINR: 40,
    maxCpmINR: 100,
    trafficTier: "Mass Market (50M+)",
    formats: ["Video Pre-Roll", "Video Mid-Roll", "Banner Displays"],
    portal: "https://zee24taas.in",
    channels: ["Zee 24 Taas Live", "Maharashtra News", "Mumbai News"],
    sports: ["Marathi Sports Coverage"]
},
{ 
    id: 44,
    name: "ABP Majha",
    niches: ["News", "Regional Content", "Live Streaming"],
    platform: "Web / App / TV",
    minCpmINR: 45,
    maxCpmINR: 110,
    trafficTier: "Mass Market (50M+)",
    formats: ["Video Pre-Roll", "Video Mid-Roll", "Banner Displays"],
    portal: "https://marathi.abplive.com",
    channels: ["ABP Majha Live", "Maharashtra News", "Mumbai News", "Pune News"],
    sports: ["Cricket News", "Maharashtra Sports"]
},
{ 
    id: 45,
    name: "News18 Lokmat",
    niches: ["News", "Regional Content", "Live Streaming"],
    platform: "Web / App / TV",
    minCpmINR: 40,
    maxCpmINR: 100,
    trafficTier: "Mass Market (50M+)",
    formats: ["Video Pre-Roll", "Video Mid-Roll", "Banner Displays"],
    portal: "https://lokmat.news18.com",
    channels: ["News18 Lokmat Live", "Maharashtra News", "Mumbai News", "Sports Time"],
    sports: ["Maharashtra Sports", "Cricket Coverage"]
},
{ 
    id: 46,
    name: "Saam TV",
    niches: ["News", "Regional Content", "Live Streaming"],
    platform: "Web / App / TV",
    minCpmINR: 35,
    maxCpmINR: 90,
    trafficTier: "Mid-Tier Premium (10M-50M)",
    formats: ["Video Pre-Roll", "Video Mid-Roll", "Banner Displays"],
    portal: "https://saamtv.com",
    channels: ["Saam TV Live", "Maharashtra News", "Mumbai News"],
    sports: ["Regional Sports News"]
},
{ 
    id: 47,
    name: "Lokmat",
    niches: ["News", "Regional Content"],
    platform: "Web / App / Print",
    minCpmINR: 40,
    maxCpmINR: 100,
    trafficTier: "Mass Market (50M+)",
    formats: ["Native In-Feed", "Banner Displays", "Video Pre-Roll"],
    portal: "https://www.lokmat.com",
    channels: ["Lokmat Marathi", "Mumbai", "Pune", "Nagpur", "Nashik"],
    sports: ["Cricket", "Maharashtra Sports"]
},
{ 
    id: 48,
    name: "NDTV Marathi",
    niches: ["News", "Regional Content", "Live Streaming"],
    platform: "Web / App / TV",
    minCpmINR: 50,
    maxCpmINR: 120,
    trafficTier: "Mid-Tier Premium (10M-50M)",
    formats: ["Video Pre-Roll", "Video Mid-Roll", "Banner Displays"],
    portal: "https://marathi.ndtv.com",
    channels: ["NDTV Marathi Live", "Maharashtra News", "Mumbai News", "Nagpur News"],
    sports: ["Cricket News", "Regional Sports"]
},
{ 
    id: 49,
    name: "Jai Maharashtra",
    niches: ["News", "Regional Content", "Live Streaming"],
    platform: "Web / App / TV",
    minCpmINR: 30,
    maxCpmINR: 80,
    trafficTier: "Niche Focused (<10M)",
    formats: ["Video Pre-Roll", "Video Mid-Roll", "Banner Displays"],
    portal: "https://jaimaharashtranews.com",
    channels: ["Jai Maharashtra Live", "Maharashtra News", "Mumbai News"],
    sports: ["Regional Sports Coverage"]
},
{ 
    id: 50,
    name: "Maharashtra Times",
    niches: ["News", "Regional Content"],
    platform: "Web / App / Print",
    minCpmINR: 50,
    maxCpmINR: 125,
    trafficTier: "Mass Market (50M+)",
    formats: ["Native In-Feed", "Banner Displays", "Video Pre-Roll"],
    portal: "https://maharashtratimes.com",
    channels: ["Maharashtra Times Marathi", "Mumbai", "Pune", "Nagpur", "Nashik"],
    sports: ["Cricket", "Maharashtra Sports"]
},
{ 
    id: 51,
    name: "DD Sahyadri",
    niches: ["News", "Regional Content", "General Entertainment"],
    platform: "TV / Digital",
    minCpmINR: 25,
    maxCpmINR: 70,
    trafficTier: "Mass Market (50M+)",
    formats: ["Video Pre-Roll", "Video Mid-Roll"],
    portal: "https://www.prasarbharati.gov.in",
    channels: ["DD Sahyadri", "Marathi News", "Marathi Cultural Programming"],
    sports: ["Regional Sports Coverage"]
},
{ 
    id: 52,
    name: "Punya Nagari",
    niches: ["News", "Regional Content"],
    platform: "Web / Print",
    minCpmINR: 30,
    maxCpmINR: 75,
    trafficTier: "Mid-Tier Premium (10M-50M)",
    formats: ["Native In-Feed", "Banner Displays"],
    portal: "https://www.dainikpunyanagari.com",
    channels: ["Punya Nagari Marathi", "Maharashtra Local News"],
    sports: ["Cricket", "Regional Sports"]
},
{ 
    id: 53,
    name: "Sakal",
    niches: ["News", "Regional Content"],
    platform: "Web / App / Print",
    minCpmINR: 40,
    maxCpmINR: 100,
    trafficTier: "Mass Market (50M+)",
    formats: ["Native In-Feed", "Banner Displays", "Video Pre-Roll"],
    portal: "https://www.esakal.com",
    channels: ["Sakal Marathi", "Pune", "Mumbai", "Nagpur", "Nashik"],
    sports: ["Cricket", "Maharashtra Sports"]
},
  { id: 54, name: "Sun News Tamil", niches: ["News", "Regional Content", "Live Streaming"], platform: "Web / App / TV", minCpmINR: 45, maxCpmINR: 110, trafficTier: "Mass Market (50M+)" },
  { id: 55, name: "Polimer News", niches: ["News", "Regional Content"], platform: "Web / App", minCpmINR: 35, maxCpmINR: 85, trafficTier: "Mass Market (50M+)" },
  { id: 56, name: "Thanthi TV", niches: ["News", "Regional Content", "Live Streaming"], platform: "Web / App / TV", minCpmINR: 40, maxCpmINR: 95, trafficTier: "Mass Market (50M+)" },
  { id: 57, name: "Puthiya Thalaimurai", niches: ["News", "Regional Content"], platform: "Web / App / TV", minCpmINR: 45, maxCpmINR: 105, trafficTier: "Mid-Tier Premium (10M-50M)" },
  { id: 58, name: "TV9 Telugu", niches: ["News", "Regional Content", "Live Streaming"], platform: "Web / App / TV", minCpmINR: 50, maxCpmINR: 120, trafficTier: "Mass Market (50M+)" },
  { id: 59, name: "NTV Telugu", niches: ["News", "Regional Content"], platform: "Web / App / TV", minCpmINR: 45, maxCpmINR: 110, trafficTier: "Mass Market (50M+)" },
  { id: 60, name: "V6 News Telugu", niches: ["News", "Regional Content"], platform: "Web / App", minCpmINR: 35, maxCpmINR: 80, trafficTier: "Mid-Tier Premium (10M-50M)" },
  { id: 61, name: "TV9 Kannada", niches: ["News", "Regional Content", "Live Streaming"], platform: "Web / App / TV", minCpmINR: 45, maxCpmINR: 110, trafficTier: "Mass Market (50M+)" },
  { id: 62, name: "Suvarna News", niches: ["News", "Regional Content"], platform: "Web / App", minCpmINR: 40, maxCpmINR: 95, trafficTier: "Mass Market (50M+)" },
  { id: 63, name: "Public TV Kannada", niches: ["News", "Regional Content"], platform: "Web / App", minCpmINR: 35, maxCpmINR: 85, trafficTier: "Mid-Tier Premium (10M-50M)" },
  { id: 64, name: "Asianet News Malayalam", niches: ["News", "Regional Content", "Live Streaming"], platform: "Web / App / TV", minCpmINR: 50, maxCpmINR: 125, trafficTier: "Mass Market (50M+)" },
  { id: 65, name: "24 News Malayalam", niches: ["News", "Regional Content"], platform: "Web / App / TV", minCpmINR: 45, maxCpmINR: 105, trafficTier: "Mass Market (50M+)" },
  { id: 66, name: "TV9 Bangla", niches: ["News", "Regional Content", "Live Streaming"], platform: "Web / App / TV", minCpmINR: 40, maxCpmINR: 100, trafficTier: "Mass Market (50M+)" },
  { id: 67, name: "Zee 24 Ghanta", niches: ["News", "Regional Content"], platform: "Web / App / TV", minCpmINR: 45, maxCpmINR: 110, trafficTier: "Mass Market (50M+)" },
  { id: 68, name: "TV9 Gujarati", niches: ["News", "Regional Content"], platform: "Web / App / TV", minCpmINR: 40, maxCpmINR: 95, trafficTier: "Mass Market (50M+)" },
  { id: 69, name: "Sandesh News", niches: ["News", "Regional Content"], platform: "Web / App / Print", minCpmINR: 35, maxCpmINR: 85, trafficTier: "Mid-Tier Premium (10M-50M)" },
  { id: 70, name: "PTC News Punjabi", niches: ["News", "Regional Content", "General Entertainment"], platform: "Web / App / TV", minCpmINR: 40, maxCpmINR: 90, trafficTier: "Mid-Tier Premium (10M-50M)" },
  { id: 71, name: "Pocket FM", niches: ["Audio", "Regional Content"], platform: "Mobile App", minCpmINR: 60, maxCpmINR: 130, trafficTier: "Mass Market (50M+)" },
  { id: 72, name: "Aha Tamil", niches: ["Regional Content", "General Entertainment"], platform: "OTT / Connected TV", minCpmINR: 110, maxCpmINR: 250, trafficTier: "Mid-Tier Premium (10M-50M)" },
  { id: 73, name: "WinZO Ad Network", niches: ["Gaming", "Entertainment"], platform: "Mobile App", minCpmINR: 50, maxCpmINR: 110, trafficTier: "Mass Market (50M+)" },
  { id: 74, name: "BQ Prime (Bloomberg)", niches: ["Finance", "Business"], platform: "Web / Desktop", minCpmINR: 190, maxCpmINR: 420, trafficTier: "Niche Focused (<10M)" },
  { id: 75, name: "Inc42 Media", niches: ["Business", "Startups"], platform: "Web / Desktop", minCpmINR: 140, maxCpmINR: 310, trafficTier: "Niche Focused (<10M)" },
    { id: 76, name: "JioCinema Ads", niches: ["OTT", "Sports", "General Entertainment"], platform: "OTT / Connected TV", minCpmINR: 100, maxCpmINR: 280, trafficTier: "Mass Market (50M+)" },
  { id: 77, name: "Manorama Online", niches: ["News", "Regional Content"], platform: "Web / Mobile App", minCpmINR: 50, maxCpmINR: 130, trafficTier: "Mass Market (50M+)" },
  { id: 78, name: "Eenadu Digital", niches: ["News", "Regional Content"], platform: "Web / Mobile App", minCpmINR: 45, maxCpmINR: 115, trafficTier: "Mass Market (50M+)" },
  { id: 79, name: "ABP Ananda", niches: ["News", "Regional Content", "Live Streaming"], platform: "Web / App / TV", minCpmINR: 40, maxCpmINR: 105, trafficTier: "Mass Market (50M+)" },
  { id: 80, name: "Mathrubhumi", niches: ["News", "Regional Content"], platform: "Web / App / Print", minCpmINR: 45, maxCpmINR: 110, trafficTier: "Mass Market (50M+)" },
  { id: 81, name: "Sakshi Post", niches: ["News", "Regional Content"], platform: "Web / App", minCpmINR: 40, maxCpmINR: 95, trafficTier: "Mass Market (50M+)" },
  { id: 82, name: "Dinakaran", niches: ["News", "Regional Content"], platform: "Web / Print", minCpmINR: 35, maxCpmINR: 85, trafficTier: "Mid-Tier Premium (10M-50M)" },
  { id: 83, name: "Divya Bhaskar", niches: ["News", "Regional Content"], platform: "Web / App", minCpmINR: 40, maxCpmINR: 100, trafficTier: "Mass Market (50M+)" },
  { id: 84, name: "Dailyhunt Network", niches: ["News", "Regional Content", "Aggregator"], platform: "Mobile App", minCpmINR: 35, maxCpmINR: 80, trafficTier: "Mass Market (50M+)" },
  { id: 85, name: "ShareChat Ad Network", niches: ["Regional Content", "Social Media"], platform: "Mobile App", minCpmINR: 45, maxCpmINR: 95, trafficTier: "Mass Market (50M+)" },
  { id: 86, name: "Moj Short Video", niches: ["Entertainment", "Regional Content"], platform: "Mobile App", minCpmINR: 50, maxCpmINR: 110, trafficTier: "Mass Market (50M+)" },
  { id: 87, name: "The Quint", niches: ["News", "Youth & Culture"], platform: "Web / Mobile App", minCpmINR: 70, maxCpmINR: 160, trafficTier: "Mid-Tier Premium (10M-50M)" },
  { id: 88, name: "ScoopWhoop", niches: ["Entertainment", "Youth & Culture"], platform: "Web / Social Platforms", minCpmINR: 60, maxCpmINR: 140, trafficTier: "Mid-Tier Premium (10M-50M)" },
  { id: 89, name: "Kuku FM", niches: ["Audio", "Regional Content"], platform: "Mobile App", minCpmINR: 55, maxCpmINR: 120, trafficTier: "Mass Market (50M+)" },
  { id: 90, name: "Glance Lockscreen Network", niches: ["News", "Gaming", "Entertainment"], platform: "Mobile Lockscreen", minCpmINR: 65, maxCpmINR: 150, trafficTier: "Mass Market (50M+)" },
  { id: 91, name: "Outlook India", niches: ["News", "Business"], platform: "Web / Magazine", minCpmINR: 90, maxCpmINR: 210, trafficTier: "Mid-Tier Premium (10M-50M)" },
  { id: 92, name: "YourStory", niches: ["Business", "Startups"], platform: "Web / Desktop", minCpmINR: 130, maxCpmINR: 290, trafficTier: "Niche Focused (<10M)" },
  { id: 93, name: "TVF (The Viral Fever)", niches: ["General Entertainment", "Youth Content"], platform: "OTT / Web", minCpmINR: 120, maxCpmINR: 270, trafficTier: "Mid-Tier Premium (10M-50M)" },
  { id: 94, name: "Namma Flix", niches: ["Regional Content", "General Entertainment"], platform: "OTT / Mobile App", minCpmINR: 50, maxCpmINR: 115, trafficTier: "Niche Focused (<10M)" },
  { id: 95, name: "Planet Marathi OTT", niches: ["Regional Content", "General Entertainment"], platform: "OTT / Connected TV", minCpmINR: 60, maxCpmINR: 135, trafficTier: "Niche Focused (<10M)" }
]
